### ISSUE TITLE
[💡 FEATURE REQUEST]: Manage services via RPC

### ISSUE THREAD

**Issue by butschster** [roadrunner-server/roadrunner#1009]
### Plugin

Service

### I have an idea!

It would be a great idea, if I am able to manage services via RPC.

For example I have a PHP application, that need sometimes to open SSH connection between two servers and keep the connection between them until I don't need it.

#### It might look like:

**Create**
```php
$rpc->call('service.Create', new Request([
     'name' => 'ssh-connection-xxx'.
     'command' => 'php app.php ssh:open --user_id=xxx',
     'process_num' => 1,
     'exec_timeout' => 0,
     'remain_after_exit' => true,
     'env' => [
          'FOO' => 'BAR'
     ],
     'restart_sec' => 1
]), Response::class);
```

**Terminate**
```php
$rpc->call('service.Terminate', new Request([
     'name' => 'ssh-connection-xxx'
]), Response::class);
```

**Restart**
```php
$rpc->call('service.Restart', new Request([
     'name' => 'ssh-connection-xxx'
]), Response::class);
```

**Status**
```php
$rpc->call('service.Status', new Request([
     'name' => 'ssh-connection-xxx'
]), Response::class);
```

**List of started services**
```php
$rpc->call('service.List', Response::class);
```

**Comment by rustatian** [comment]
Hey @butschster. Wonderful idea 👍🏻 ⚡

**Comment by butschster** [comment]
Thank you! You are the best!

**Comment by butschster** [comment]
@rustatian could you provide information about actual RPC methods?

**Comment by rustatian** [comment]
> @rustatian could you provide information about actual RPC methods?

Sure, will be in the release notes 😃
