### ISSUE TITLE
[🐛 BUG]: FORWARDED header not parsed

### ISSUE THREAD

**Issue by digitalkaoz** [roadrunner-server/roadrunner#1018]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

actually the common `FORWARDED` header is not parsed (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded). relates to #644 

### Version

2.8.0

**Comment by rustatian** [comment]
Hey @digitalkaoz. Could you please attach some request samples which RR can't handle?
