### ISSUE TITLE
[🐛 BUG]: `version` can't be passed as inline option

### ISSUE THREAD

**Issue by nunomaduro** [roadrunner-server/roadrunner#1021]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hi, 

The `version` on the `.rr.yaml` can't be passed as inline option `-o`. At Laravel, we would like to set this parameter based on the roadrunner binary used, so we don't have to ask all the existing library users to update their `.rr.yaml` files.

https://github.com/laravel/octane/issues/479

### Version

2.8.1

**Comment by rustatian** [comment]
Hey @nunomaduro. Yeah, the version check is made before the configuration options overwrite. I'll fix that in the 2.8.2 today, thanks for the report.

**Comment by rustatian** [comment]
@nunomaduro https://github.com/roadrunner-server/roadrunner/releases/tag/v2.8.2 Done 🚀
