### ISSUE TITLE
[🐛 BUG]: Call of kv.TTL return unexpected string format

### ISSUE THREAD

**Issue by antikirra** [roadrunner-server/roadrunner#1024]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

**Final error:**
Spiral\RoadRunner\KeyValue\Cache::dateFromRfc3339String(): Return value must be of type DateTimeImmutable, bool returned (cause `getMultipleTtl` return unexpected string format `4319h59m53s` instead of `2022-08-21T03:36:12+00:00`)

**Trace:**
```
#0 /app/vendor/spiral/roadrunner-kv/src/Cache.php(161): Spiral\RoadRunner\KeyValue\Cache->dateFromRfc3339String()
#1 /app/vendor/spiral/roadrunner-kv/src/Cache.php(123): Spiral\RoadRunner\KeyValue\Cache->getMultipleTtl()
#2 /app/src/Repository/ConfirmationRepository.php(71): Spiral\RoadRunner\KeyValue\Cache->getTtl()
```

**Expected:**
Call kv.TTL always return datetime string Rfc3339 for any kv driver

----

**Success for memory driver**

rr.yml
```yml
kv:
  cache:
    driver: memory
    config:
      interval: 1
```
./vendor/spiral/roadrunner-kv/src/Cache.php
```php
public function getMultipleTtl(iterable $keys = []): iterable
{
        $response = $this->createIndex(
            $this->call('kv.TTL', $this->requestKeys($keys))
        );
        /// ...
        foreach ($keys as $key) {
            $response[$key]->getTimeout(); // string "2022-08-21T03:36:12+00:00" <-- it's ok :)
        }
}
```

----

**Fail for redis driver**

rr.yml
```yml
kv:
  cache:
    driver: redis
    config:
      addrs:
        - "cache:6379"
```
./vendor/spiral/roadrunner-kv/src/Cache.php
```php
public function getMultipleTtl(iterable $keys = []): iterable
{
        $response = $this->createIndex(
            $this->call('kv.TTL', $this->requestKeys($keys))
        );
        /// ...
        foreach ($keys as $key) {
            $response[$key]->getTimeout(); // string "4319h59m53s" <-- it's WRONG!!!
        }
}
```

### Version

2.7.4 && 2.8.1 (suppose, any version)

**Comment by rustatian** [comment]
Hey @antikirra, thanks for the report, I'll check that.

**Comment by rustatian** [comment]
@antikirra Redis driver according to the specs returns the remaining time in seconds, but not the expiration time in the RFC3339 format.
I guess that the issue in the PHP client library which incorrectly parses the `-1` (no TTL) and `-2` (no key) returned values.

**Comment by antikirra** [comment]
@rustatian may be problem in redis plugin?
https://github.com/roadrunner-server/redis/blob/7645cc291c7efedd7f30889e809b3b6b47881238/kv/kv.go#L242

**Comment by rustatian** [comment]
> @rustatian may be problem in redis plugin? https://github.com/roadrunner-server/redis/blob/7645cc291c7efedd7f30889e809b3b6b47881238/kv/kv.go#L242

RR doesn't interpret the values. So, the RR Redis driver just returns the value obtained from the Redis.

**Comment by antikirra** [comment]
> > @rustatian may be problem in redis plugin? https://github.com/roadrunner-server/redis/blob/7645cc291c7efedd7f30889e809b3b6b47881238/kv/kv.go#L242
> 
> RR doesn't interpret the values. So, the RR Redis driver just returns the value obtained from the Redis.

Is it right behavior? I thought, that rr should be provide ubiquitous interface for any kv drivers, because kv.memory.TTL return RFC3339 string https://github.com/roadrunner-server/memory/blob/2124cbe7fa93d5808300e878215dc24e8a04b811/memorykv/kv.go#L183

**Comment by rustatian** [comment]
At the moment this is the right behavior. I will think about unifying it.

**Comment by rustatian** [comment]
We will discuss this with @butschster (PHP team leader) on how to better handle that. Most probably RR will convert the payload into the RFC3339 time format, and exclude from the return payload keys with -1 and -2 values.
