### ISSUE TITLE
[🐛 BUG]: `rr workers -i` do not return all services

### ISSUE THREAD

**Issue by OO00O0O** [roadrunner-server/roadrunner#1033]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I have running 2 services, that are defined in `rr.yaml` under `service`.
They are not displayed in `rr workers -i` inspect window.

### Version

2.8.2

**Comment by rustatian** [comment]
Hey @OO00O0O, thanks for the report. Will be fixed in the next bugfix release.
