### ISSUE TITLE
[💡 FEATURE REQUEST]: RPC documentation

### ISSUE THREAD

**Issue by OO00O0O** [roadrunner-server/roadrunner#1045]
### Plugin

Server

### I have an idea!

Would be nice to have documentation for RPC methods and arguments. 

Lowest expectation for this would be, having an explanation how to read Go code to understand what methods could be called, and with what arguments.

**Comment by rustatian** [comment]
Thanks for the FR @OO00O0O, that's a good idea.

**Comment by rustatian** [comment]
fixed: https://github.com/roadrunner-server/roadrunner-docs/commit/d24a89e23018c799cb09fdedcc7547b937ba1050

Will be in the new `v2023.1.0` docs. Thanks @OO00O0O 👍🏻
