### ISSUE TITLE
[💡 FEATURE REQUEST]: `workers -i` services has no information about amount of them running

### ISSUE THREAD

**Issue by OO00O0O** [roadrunner-server/roadrunner#1053]
### I have an idea!

Now `workers -i` show `services` but it's missing column of how many of that service instances are running. It's hard to know if I have to multiply memory by amount of instances or not. 

MVP would be NUM INSTANCES column or one instance per line.

Maybe current state of service too: waiting(`remain_after_exit: true`), running, stoping(`exec_timeout`)

**Comment by rustatian** [comment]
Hey @OO00O0O. Yeah, agree. Will be added in `2.10`. Thanks for the FR 👍🏻

**Comment by rustatian** [comment]
Hey @OO00O0O 👋🏻 . RR will show all the processes. There was a bug that prevented showing info about all processes. You'll see every process with its resources, memory, PID, etc.

That feature closes by: https://github.com/roadrunner-server/service/pull/12
