### ISSUE TITLE
[🧹 CHORE]: Trim spaces and new lines from cli output

### ISSUE THREAD

**Issue by OO00O0O** [roadrunner-server/roadrunner#1060]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

Would be nice to have nicer output, like first lines. Maybe RR could trim line ends from whitespaces like `\t \n` etc.

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/766148/158807714-daeea958-7769-4d4e-85a8-ecd92d1338b2.png">

**Comment by rustatian** [comment]
Done: https://github.com/roadrunner-server/service/commit/83bce5ff6bf5cfbfd81c8c62b5d0962c6f82685f
