### ISSUE TITLE
[🐛 BUG]: Websocket access validator requests don't send cookies

### ISSUE THREAD

**Issue by steffendietz** [roadrunner-server/roadrunner#1064]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Before accepting a Websocket connection, the received request is mapped to a `PSR-7` request object and sent to PHP for access validation.

It seems, that during the translation to `PSR-7` critical information like Cookies are lost. This in turn prevents use of `AuthScope`s in spiral.

The request mapping seems quite a bit [more involved in the http-handler](https://github.com/roadrunner-server/http/blob/a36632c8dc26a8407295913a540e7adda3b8c237/handler/request.go#L70) than in the [access](https://github.com/roadrunner-server/websockets/blob/e4a8f6be0be879aa2c07f994e741667e8e00aaeb/validator/access_validator.go#L103) [validators](https://github.com/roadrunner-server/websockets/blob/e4a8f6be0be879aa2c07f994e741667e8e00aaeb/validator/access_validator.go#L71).

Could you maybe have a look at it?

### Version

2.8.4

**Comment by rustatian** [comment]
Hey @steffendietz 👋🏻 , thanks for the report. Could you please provide some samples to reproduce that?

**Comment by steffendietz** [comment]
Hi. So I have set up a reproduction project here: https://github.com/steffendietz/ws_reproduction

From the `README.md`. I hope you can track down the bug with this.

## Reproduce

### HTTP Request

From the host run

```
curl "http://localhost:8181" -H "Cookie: csrf-token=World; token=Hello"
```

Observe output in the container console

```
INFO server          
[php info] Attributes: Array
(
)

 []
[php info] CookieData: Array
(
    [csrf-token] => World
    [token] => Hello
)

 []
```

### WS Request

From the host run

```
curl "http://localhost:8181/ws" -H "Cookie: csrf-token=World; token=Hello" -H "Sec-WebSocket-Version: 13" -H "Sec-WebSocket-Key: SGVsbG8gb2xkIHdvcmxkIQ==" -H "Connection: keep-alive, Upgrade" -H "Upgrade: websocket"
```

Observe output in the container console

```
INFO server          
[php info] Attributes: Array
(
    [ws:joinServer] => 1
)

 []
[php info] CookieData: Array
(
)

 []
```

**Comment by rustatian** [comment]
@steffendietz Got it, thank you 👍🏻

**Comment by rustatian** [comment]
I'll dig into it today, so if it is something easy to fix, it'll be released tomorrow in the `v2.8.6`.

**Comment by steffendietz** [comment]
Sounds great. I suspect it has something to do with the difference how the go http requests are mapped to the PSR-7 struct.

Maybe it would make sense to DRY this up regardless and extract the `Request` struct defined [here](https://github.com/roadrunner-server/websockets/blob/e4a8f6be0be879aa2c07f994e741667e8e00aaeb/validator/access_validator.go#L28) and [here](https://github.com/roadrunner-server/http/blob/a36632c8dc26a8407295913a540e7adda3b8c237/handler/request.go#L26) and the mapping code into their own sub-package.

Thanks for having a look. 💪 🚀

**Comment by rustatian** [comment]
> extract the Request struct defined [here](https://github.com/roadrunner-server/websockets/blob/e4a8f6be0be879aa2c07f994e741667e8e00aaeb/validator/access_validator.go#L28) and [here](https://github.com/roadrunner-server/http/blob/a36632c8dc26a8407295913a540e7adda3b8c237/handler/request.go#L26) and the mapping code into their own sub-package

Yeah, this structure will be moved to the `roadrunner-server/api`. Now I have a chance to do that 😃

**Comment by rustatian** [comment]
@steffendietz Found the problem. I forgot to add them to the request, which will be an easy fix. I'll release a bugfix version tomorrow.

**Comment by rustatian** [comment]
@steffendietz https://github.com/roadrunner-server/roadrunner/releases/tag/v2.8.6

**Comment by steffendietz** [comment]
Thanks a lot! I will test as soon as the release assets are generated. 👍

**Comment by rustatian** [comment]
I guess, it'll be 2.8.7, because linters failed in 2.8.6 which leads to failure in build generation.

**Comment by rustatian** [comment]
@steffendietz https://github.com/roadrunner-server/roadrunner/releases/tag/v2.8.7

**Comment by steffendietz** [comment]
@rustatian Sorry, I didn't come around with feedback earlier, but everything works as expected now. Thanks for your 🚀 support.
