### ISSUE TITLE
[💡 FEATURE REQUEST]: .env file path configuration in .rr.yaml

### ISSUE THREAD

**Issue by OO00O0O** [roadrunner-server/roadrunner#1077]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

By default - none.

.rr.yaml example
```
version: '2.7'
envfile: .env
```

**Comment by rustatian** [comment]
Hey @OO00O0O 👋🏻 I guess it's more like a feature request 😃 Thank you for the proposal. Let's wait for more feedback because we already have a flag to load `.env` files.
