### ISSUE TITLE
[💡 FEATURE REQUEST]: handle failed jobs when worker haven't responded

### ISSUE THREAD

**Issue by tntrex** [roadrunner-server/roadrunner#1089]
### Plugin

JOBS

### I have an idea!

Currently, when PHP worker process exits without responding back to RoadRunner (for example, a PHP fatal error occurred or the process got `kill -9`ed), RoadRunner will send job to the next worker over and over again.

Some logs to demonstrate case when PHP process fails with fatal error:

```
{"log":"[15-Apr-2022 15:52:04 UTC] PHP Fatal error:  Allowed memory size of 5368709120 bytes exhausted (tried to allocate 671088640 bytes) in /home/space/app/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Memory.php on line 104\n","stream":"stderr","time":"2022-04-15T15:52:04.944959128Z"}
{"log":"network error, worker will be restarted\u0009{\"reason\": \"network\", \"pid\": 313, \"internal_event_name\": \"EventWorkerError\", \"error\": \"sync_worker_exec: Network:\\n\\tsync_worker_exec_payload: EOF\"}\n","stream":"stderr","time":"2022-04-15T15:52:05.629079115Z"}
{"log":"{\"level\":\"error\",\"ts\":1650037925.6289606,\"logger\":\"jobs\",\"msg\":\"job processed with errors\",\"error\":\"sync_worker_exec: Network:\\n\\tsync_worker_exec_payload: EOF\",\"ID\":\"1b267a0b-06a8-4882-ab96-5ad140042295\",\"start\":1650031196.5930843,\"elapsed\":6729.035874425}\n","stream":"stderr","time":"2022-04-15T15:52:05.629148259Z"}
{"log":"{\"level\":\"error\",\"ts\":1650037925.6775649,\"logger\":\"jobs\",\"msg\":\"job execute failed\",\"error\":\"sync_worker_exec: Network:\\n\\tsync_worker_exec_payload: EOF\"}\n","stream":"stderr","time":"2022-04-15T15:52:05.677804664Z"}
```

It will be great if we can configure how RoadRunner should handle such tasks per each pipeline:

1. to preserve current behavior by default
2. to send them to other pipeline (if we want to schedule them later in our worker)
3. to just drop them

**Comment by rustatian** [comment]
Hey @hustlahusky. In the `v2.10` will be a new `Job` option: `auto_ack`. You'd be able to ack such jobs after RR get it from the driver but before the actual worker processing starts.

**Comment by rustatian** [comment]
Hey @hustlahusky. This will be covered by docs, since the `v2.10` you'll be able to use the `auto_ack` job option to ACK the job right after RR receives it from the queue (similar to rabbitmq auto_ack).
