### ISSUE TITLE
[🧹 CHORE]: HTTP. Wrong response status code exception. Better looking error message

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/roadrunner#1107]
### No duplicates 🥲.

- [x] I have searched for a similar issue.

### What should be improved or cleaned up?

If I return incorrect HTTP status code in response from php worker when I get message like this:

> 2022-04-28T14:00:52.874Z    ERROR   http            internal server error   {"message": "http_plugin: 2022/04/28 14:00:52 http: panic serving 172.18.0.3:49218: invalid WriteHeader code 300000\ngoroutine 35 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1825 +0xbf\npanic({0x15e34c0, 0xc0007fd330})\n\truntime/panic.go:844 +0x258\nnet/http.checkWriteHeaderCode(...)\n\tnet/http/server.go:1111\nnet/http.(*response).WriteHeader(0xc0008360e0, 0x493e0)\n\tnet/http/server.go:1145 +0x819\ngithub.com/roadrunner-server/http/v2/handler.(*Handler).Write(0xc00092c000, 0xc000896240, {0x1ad3c00, 0xc0008360e0})\n\tgithub.com/roadrunner-server/http/v2@v2.14.1/handler/response.go:61 +0x2f2\ngithub.com/roadrunner-server/http/v2/handler.(*Handler).ServeHTTP(0xc00092c000, {0x1ad3c00, 0xc0008360e0}, 0xc0000c0a00)\n\tgithub.com/roadrunner-server/http/v2@v2.14.1/handler/handler.go:168 +0x9b5\ngithub.com/roadrunner-server/http/v2.(*Plugin).ServeHTTP(0xc000195600, {0x1ad3c00, 0xc0008360e0}, 0xc0000c0a00)\n\tgithub.com/roadrunner-server/http/v2@v2.14.1/plugin.go:292 +0x20e\ngithub.com/roadrunner-server/headers/v2.(*Plugin).Middleware.func1({0x1ad3c00, 0xc0008360e0}, 0xc0000c0a00)\n\tgithub.com/roadrunner-server/headers/v2@v2.11.0/plugin.go:70 +0x2bc\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x1ad3c00?, 0xc0008360e0?}, 0xc000065400?)\n\tnet/http/server.go:2084 +0x2f\nnet/http.serverHandler.ServeHTTP({0xc0008d8390?}, {0x1ad3c00, 0xc0008360e0}, 0xc0000c0a00)\n\tnet/http/server.go:2916 +0x43b\nnet/http.(*conn).serve(0xc0008a4000, {0x1ad4d08, 0xc0008b46f0})\n\tnet/http/server.go:1966 +0x5d7\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3071 +0x4db\n"}

This message is very scary for php developer. I propose to make the message clearer and without stacktrace.

**Comment by rustatian** [comment]
done by: https://github.com/roadrunner-server/http/commit/14dc4130d13310bf38f3ee06db7b9a0e8846f5e4
