### ISSUE TITLE
[🐛 BUG]: `reset` command gets stuck when using output redirection

### ISSUE THREAD

**Issue by maximal** [roadrunner-server/roadrunner#1108]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hi there!

I’m trying to use `rr reset` in my GitLab CI/CD workflow to restart application workers but it gets stuck every time.
I tried to dig deeper and found out that `reset` command never ends when we use output redirection (which obviously used to get CI/CD pipeline log):

```sh
# goes fine
/path/to/rr reset -c /path/to/.rr.yaml

# gets stuck with constantly growing rr.log file
/path/to/rr reset -c /path/to/.rr.yaml > rr.log
```

Isn’t that a bug? Or, what am I doing wrong? How can I reset workers during my CI/CD pipeline?

### Version

* RoadRunner v2.9.1 (latest stable)
* Debian 11 ×64 (latest stable)

EDIT (@rustatian):
- [x] Replace used library with a stdlib.
- [x] Extend `--silent` flag to all commands.

**Comment by rustatian** [comment]
Hey @maximal, nice to meet you 👋🏻. Thanks for the report. This is a known issue with the progress-bar writer library we use. It hangs on the first write to the stderr/stdout. 
So, it'll not grow, you'll see only the first write: `Res...`. I can guess, that the file growth is a pipeline issue.

**Comment by maximal** [comment]
@rustatian, it grows. As I understand, the library constantly writing `\rRes...` to the output. Thus the file size will increase.
Anyway, the process should end regardless of the output options/pipes/etc I guess.

Any methods to disable the output for `reset` completely (or just the “progress” thing)?

**Comment by rustatian** [comment]
> As I understand, the library constantly writing \rRes... to the output

It hangs on the first write.
![image](https://user-images.githubusercontent.com/8040338/166001670-b5d00a50-4aee-42b8-8e50-4ee5ce9a2b0c.png)

But if you write to some shared file or write in a loop, it'll undoubtedly grow. I mean, write-per-run.

> Any methods to disable the output for reset completely (or just the “progress” thing)?

We have a `--silent` flag, but it applies only to the startup message. Now we have a reason to extend the relevant field for that flag.
I'll put it in the `v2.9.3` milestone (release date: next Thursday)

**Comment by maximal** [comment]
Yeah, I tried that `--silent` flag, but it won’t help.

As for growing. In the terminal you only see the `Res...` message because the library sends `\r` character in every iteration, which returns the caret to the beginning of the line.
If you could watch file size in bytes it’ll grow during this process. You cat open the log file in any hex editor and you’ll see:
```
\rRes...\rRes...\rRes...\rRes...\rRes...\rRes...\rRes...\rRes...\rRes...\rRes... ... ... ...
```

Thanks for accepting the issue!

**Comment by maximal** [comment]
Yeah, I tried that `--silent` flag, but it won’t help.

As for growing. In the terminal you only see the `Res…` message because the library sends `\r` character in every iteration (maybe along with some other control characters like terminal color setting or similar ones), which returns the caret to the beginning of the line.
If you could watch file size in bytes it’ll grow during this process. You cat open the log file in any hex editor and you’ll see:
```
\rRes…\rRes…\rRes…\rRes…\rRes…\rRes…\rRes…\rRes…\rRes…\rRes… ... ... ...
```
or something like that.

Thanks for accepting the issue!

**Comment by maximal** [comment]
Yeah, I tried that `--silent` flag, but it won’t help.

As for growing. In the terminal you only see the `Res…` message because that progress library sends `\r` character in every iteration (maybe along with some other control characters like terminal color setting or similar ones), which returns the caret to the beginning of the line.
If you could watch the file size in bytes it’ll grow during this (one) process. You can open the log file in any hex editor and you’ll see:
```
\rRes…\rRes…\rRes…\rRes…\rRes…\rRes…\rRes…\rRes…\rRes…\rRes… ... ... ...
```
or something like that.

Thanks for accepting the issue!

**Comment by rustatian** [comment]
> Thanks for accepting the issue!

My pleasure.

> As for growing

I checked with `du -sh` and you're right. The file is growing. The bizarre behavior of that library. I'll consider replacing it with stdlib. Thanks for pointing that out 👍🏻

**Comment by maximal** [comment]
You’re welcome!
