### ISSUE TITLE
[💡 FEATURE REQUEST]: Increase error message length

### ISSUE THREAD

**Issue by ykweb** [roadrunner-server/roadrunner#1127]
### Plugin

Logger

### I have an idea!

Encountered an error creating php worker
But the length of the message does not allow us to understand what the error is.
`{"level":"ERROR","ts":"2022-05-11T15:38:15.012+0300","logger":"jobs        ","msg":"job execute failed","error":"goridge_frame_receive: CRC verification failed, bad header: TypeError {#209\n"}`

The full message looked like this:
`TypeError {#209
  #message: "Symfony\Component\Console\Application::__construct(): Argument #1 ($name) must be of type string, App\Kernel given, called in /app/bin/jobs on line 17"
  #code: 0
  #file: "./vendor/symfony/console/Application.php"
  #line: 91
  trace: {
`

**Comment by rustatian** [comment]
Hey @ykweb 👋🏻 . Thanks for the contribution. I'll try to find a way to show an entire error message during the worker boot-up.

**Comment by rustatian** [comment]
Source: https://github.com/roadrunner-server/goridge/blob/master/internal/receive.go#L53
