### ISSUE TITLE
[💡 FEATURE REQUEST]: Kafka driver

### ISSUE THREAD

**Issue by Smolevich** [roadrunner-server/roadrunner#1128]
### Plugin

JOBS

### I have an idea!

I have an idea, listen to me!!
I propose to add support kafka driver in jobs like as [amqp](https://roadrunner.dev/docs/beep-beep-jobs#configuration-amqp-driver) driver
**Reason:**
Event-driven architecture based on events in different topics in kafka often requires many consumers with some logic of processing events in topics

**Comment by rustatian** [comment]
Hey @Smolevich, thanks for contributing. Planned for the `v2.12.0`

EDIT: `v2.11.0`
