### ISSUE TITLE
[🐛 BUG]: unknown status code from worker

### ISSUE THREAD

**Issue by Meroje** [roadrunner-server/roadrunner#1136]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

My APIs are making use of custom 4xx codes to signal specific conditions but the http plugin is now transforming those to 500s since https://github.com/roadrunner-server/http/commit/14dc4130d13310bf38f3ee06db7b9a0e8846f5e4. There doesn't seem to be a way to disable and/or configure the list of codes ?

### Version

2.9.3+

### Relevant log output

```shell
{"level":"debug","ts":1652794756.8272269,"logger":"rpc","msg":"plugin was started","address":"tcp://127.0.0.1:6001","list of the plugins with RPC methods:":["status","informer","resetter","metrics"]}
[INFO] RoadRunner server started; version: 2.9.3, buildtime: undefined
2022-05-17T15:39:18.669+0200	ERROR	http        	write response error	{"start": "2022-05-17T15:39:18.587+0200", "elapsed": "81.714052ms", "error": "unknown status code from worker: 498"}
^Cstop signal received, grace timeout is: 30 seconds
```

**Comment by rustatian** [comment]
Hey @Meroje, nice to meet you 👋🏻. I'm curious. On the prev versions, should be an error in that case: https://github.com/roadrunner-server/roadrunner/issues/1107.

**Comment by Meroje** [comment]
Hi :) I'm not seeing any log when using a 4xx code (498 in the log I posted above), I guess the issue you linked was about going beyond 999 (or 599) ?

edit: the godoc indeed mentions this "The provided code must be a valid HTTP 1xx-5xx status code."

**Comment by rustatian** [comment]
Yeah, I checked this case. Agreed; I'll revert this change.

**Comment by rustatian** [comment]
I'll limit the status code to fit the documentation (<600).

---
The fix will be in `2.10.1`, scheduled on Thursday (19th of May).

**Comment by Meroje** [comment]
Sounds good to me thank you :)

**Comment by rustatian** [comment]
My pleasure 🤝 And sorry for the bad UX.
