### ISSUE TITLE
[🐛 BUG]: RR samples a large log message in STDERR on few chunks

### ISSUE THREAD

**Issue by 7krasov** [roadrunner-server/roadrunner#1171]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hi everyone,
I'm reporting an issue discussed here https://github.com/roadrunner-server/roadrunner/discussions/1170
I would like to have a log message entire when I'm logging to STDERR stream (via PHP, Monolog, StreamHandler('php://stderr')) from the worker, but it samples it on parts when it is large (more than about 32770 characters)

Could you please add some option in RR config to increase a message sample size? So I could have my message entire and not split on parts

1) reproduce RR log message sampling (via worker)

`docker-compose exec pss_rr /usr/local/bin/rr serve -d -w /var/app -c /var/app/worker/.rr-test-log-sampling.yaml`

`.rr-test-log-sampling.yaml`

```
version: "2.7"
rpc:
  listen: tcp://127.0.0.1:6002

server:
  command: "php /var/app/worker/reproduce_stderr_message_sampling.php"

http:
  address: 0.0.0.0:8090
  pool:
    num_workers: 4
    debug: false

logs:
  mode: development
  output: stdout
  err_output: stderr
  encoding: console

```

`reproduce_stderr_message_sampling.php`

```
<?php

use Monolog\Formatter\LogstashFormatter;
use Monolog\Handler\StreamHandler;
use Monolog\Logger;
use Nyholm\Psr7\Factory\Psr17Factory;
use Spiral\RoadRunner\Http\PSR7Worker;
use Spiral\RoadRunner\Worker;

$rootPath = __DIR__ . '/..';
require $rootPath . '/vendor/autoload.php';
//"spiral/roadrunner": "2.10.4"

$worker = Worker::create();
$psrFactory = new Psr17Factory();
$workerPsr = new PSR7Worker($worker, $psrFactory, $psrFactory, $psrFactory);

$streamHandler = new StreamHandler(('php://stderr'));
$streamHandler->setFormatter(new LogstashFormatter('STDERR TEST LOG FORMATTER'));
$logger = new Logger('STDERR TEST LOGGER', [$streamHandler]);

$responseFactory = new Psr17Factory();
$preparedResponse = $responseFactory->createResponse(200);
$preparedResponse->withHeader('content-type', 'application/json');
$preparedResponse->getBody()->write('{}');

while ($req = $workerPsr->waitRequest()) {
    //a payload message will be 32600 chars A length + logstash json wrapper
    $logger->info(str_pad('', 32600, 'A'));
    $workerPsr->respond($preparedResponse);
}


```

Request: `GET http://0.0.0.0:8090`

2) reproduce no sampling (without RR worker, just PHP script running)

`docker-compose exec pss_rr php /var/app/worker/test.php`

`test.php`

```
<?php

use Monolog\Formatter\LogstashFormatter;
use Monolog\Handler\StreamHandler;
use Monolog\Logger;

$rootPath = __DIR__ . '/..';
require $rootPath . '/vendor/autoload.php';
//"spiral/roadrunner": "2.10.4"

$streamHandler = new StreamHandler(('php://stderr'));
$logger = new Logger('STDERR TEST LOGGER', [$streamHandler]);
$streamHandler->setFormatter(new LogstashFormatter('STDERR TEST LOG FORMATTER'));
//a payload message will be 32600 chars A length + logstash json wrapper
$logger->info(str_pad('', 32600, 'A'));

```

Thank you!

### Version

rr version 2.10.4 (build time: 2022-06-10T23:29:30+0000, go1.18.3)
composer package "spiral/roadrunner": "2.10.4"

### Relevant log output

```shell
1) Sampling

2022-06-12T15:16:22.997Z	DEBUG	rpc         	plugin was started	{"address": "tcp://127.0.0.1:6002", "list of the plugins with RPC methods:": ["resetter", "informer"]}
[INFO] RoadRunner server started; version: 2.10.4, buildtime: 2022-06-10T23:29:30+0000
2022-06-12T15:16:23.073Z	DEBUG	server      	worker is allocated	{"pid": 271, "internal_event_name": "EventWorkerConstruct"}
2022-06-12T15:16:23.194Z	DEBUG	server      	worker is allocated	{"pid": 268, "internal_event_name": "EventWorkerConstruct"}
2022-06-12T15:16:23.276Z	DEBUG	server      	worker is allocated	{"pid": 270, "internal_event_name": "EventWorkerConstruct"}
2022-06-12T15:16:23.369Z	DEBUG	server      	worker is allocated	{"pid": 272, "internal_event_name": "EventWorkerConstruct"}
2022-06-12T15:16:23.370Z	DEBUG	http        	http server was started	{"address": "0.0.0.0:8090"}
2022-06-12T15:16:28.631Z	INFO	server      	{"@timestamp":"2022-06-12T15:16:28.631193+00:00","@version":1,"host":"1b40d2501046","message":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
...
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","type":"STDERR TEST LOG FORMATTER","channel":"STDERR TEST LOGGER","leve
2022-06-12T15:16:28.631Z	INFO	server      	l":"INFO","monolog_level":200}

2) No sampling

{"@timestamp":"2022-06-12T15:18:02.875125+00:00","@version":1,"host":"1b40d2501046","message":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
...
AAAAAAAAAAAAAAAAAAA","type":"STDERR TEST LOG FORMATTER","channel":"STDERR TEST LOGGER","level":"INFO","monolog_level":200}
```

**Comment by rustatian** [comment]
Hey @7krasov 👋🏻 
The problem was not the sampling but the `stderr` buffer size. I've increased it to 64kb, which should be enough for the one log-send.

**Comment by rustatian** [comment]
That is the default pipe capacity for Linux (https://linux.die.net/man/7/pipe, look at the pipe capacity paragraph).

**Comment by 7krasov** [comment]
Hi @rustatian :wave: 
Thanks for the investigation!
I see here that "Since Linux 2.6.11, the pipe capacity is 65536 bytes.". And I understand that the log message length > 65536 bytes (64k) will be always split. Well, 64k is better than now ( I suppose it is 32k). Could we adjust to 64к at least? It will be better anyway so I can split my messages for > 64k within PHP less often than now ... As I understood, my example test should pass with 64k.
Also, If it has an influence on performance, maybe we could have some option in config to adjust this size...
What do you think?

**Comment by rustatian** [comment]
> I suppose it is 32k

Yeah, correct :)

> Also, If it has an influence on performance, maybe we could have some option in config to adjust this size...

It's not a problem; performance will be the same since we allocate a buffer only once.

**Comment by rustatian** [comment]
>  As I understood, my example test should pass with 64k.

Yeah, correct

> Could we adjust to 64к at least?

Yeah, the limit will be increased to 65536 bytes in the `v2.10.5`.

**Comment by 7krasov** [comment]
Thank you for your help!

**Comment by rustatian** [comment]
Just to be sure, please, keep in mind, that `monolog` adds additional fields to your structured log, like 
`{"level":"info","ts":1655979301.839286,"logger":"server","msg":"{\"@timestamp\":\"2022-06-23T10:15:01.839179+00:00\",\"@version\":1......`

So, if you send a `$logger->info(str_pad('', 65536, 'A'));` log like this one, it'll be split into 2 parts, because it would be 65536 + `{"level":"info","ts":1655979301.839286,"logger":"server","msg":"{\"@timestamp\":\"2022-06-23T10:15:01.839179+00:00\",\"@version\":1......` etc.

**Comment by 7krasov** [comment]
Yeah, I understand that my message is being extended with Monolog LogstashFormatter or any other formatter so my max payload length by a fact is less than 64k. I think we left a rather clear explanation for other users who will bump into that :muscle: 
Thanks Valery!

**Comment by rustatian** [comment]
My pleasure @7krasov 👍🏻
