### ISSUE TITLE
[🧹 CHORE]: Extend existing metrics

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/roadrunner#1194]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

It would be nice to have the following metrics:

`gRPC` plugin: [Server-side interceptors](https://github.com/roadrunner-server/roadrunner/issues/973)
- [x] Response codes
- [x] Latency
- [x] RPM

`Jobs` plugin:
- [x] Latency
- [x] RPM

`temporal` plugin: [interceptors](https://github.com/temporalio/sdk-go/blob/master/interceptor/interceptor.go)
- ?? (there are a lot of metrics already available)

**Comment by cv65kr** [comment]
Hi @rustatian I think you can close this issue, metrics mentioned in ticket existing for gRPC and Temporal.

**Comment by rustatian** [comment]
Yeah, thanks 👍🏻
