### ISSUE TITLE
[🐛 BUG]: proto file 'first.proto' does not exists

### ISSUE THREAD

**Issue by IgorDePaula** [roadrunner-server/roadrunner#1207]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I installed the project via composer. But on run it, he crashes with error message: proto file 'first.proto' does not exists.

![Captura de tela de 2022-07-09 12-52-03](https://user-images.githubusercontent.com/2833993/178113173-336dfc09-b7f4-4dbd-b68c-ee25c3fe4ea6.png)

### Version (rr --version)

rr version 2.10.6 (build time: 2022-07-07T11:00:09+0000, go1.18.3), OS: linux, arch: amd64

### Relevant log output

```shell
handle_serve_command: Init error:
	endure_initialize:
	endure_internal_init: Function call error:
	endure_call_init_fn:
	grpc_plugin_init:
	grpc_plugin_config: proto file 'first.proto' does not exists
```

**Comment by rustatian** [comment]
Hello 👋 
You used a configuration sample. Inspect your rr.yaml config and remove not needed plugins.

**Comment by rustatian** [comment]
You may have a look at the docs: https://roadrunner.dev/docs/php-worker/2.x/en

**Comment by IgorDePaula** [comment]
@rustatian I got run it, but your php example has 2 errors, on line 20 and 28, the correct is ```\Throwable $e```, not ```\Throwable``` only

**Comment by rustatian** [comment]
Could you please send a PR to the https://github.com/spiral/docs ?
