### ISSUE TITLE
[🐛 BUG]: RR doesn't respect `http.pool.allocate_timeout`

### ISSUE THREAD

**Issue by Warxcell** [roadrunner-server/roadrunner#1226]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I have 

```
http:
    address: ${HOST}:${PORT}
    pool:
        debug: ${RR_DEBUG}
        num_workers: ${RR_WORKERS}
        max_jobs: 0
        allocate_timeout: 120s
```

but it tells 

```
php 2022-07-25T13:53:05.610Z    ERROR    http            execute    {"start": "2022-07-25T13:52:05.602Z", "elapsed": "1m0.007540715s", "error": "failed to spawn a worker, possible reasons: https://roadrunner.dev/docs/known-issues-allocate-timeout/2.x/en"}
```
elapsed is 1m, so it doesn't respect 120s (2m)

and there is a typo in the docs: https://roadrunner.dev/docs/http-available-middleware/2.x/en

it should be `http.pool.allocate_timeout` not `pool.allocate_timeout`.

### Version (rr --version)

2.11.0-beta.1

### Relevant log output

```shell
php 2022-07-25T13:53:05.610Z    ERROR    http            execute    {"start": "2022-07-25T13:52:05.602Z", "elapsed": "1m0.007540715s", "error": "failed to spawn a worker, possible reasons: https://roadrunner.dev/docs/known-issues-allocate-timeout/2.x/en"}
```

**Comment by rustatian** [comment]
Hey @Warxcell 👋🏻 
The workers' pool is not an `http` plugin property.
But `allocate_timeout` is the property of the `pool`. It can be `jobs.pool.allocate_timeout`, `http.pool...`, `grpc.pool...`, etc. Thus in the docs, we used a more general term, `pool.allocate_timeout`.

**Comment by rustatian** [comment]
Regarding the first part of the issue, about `allocate_timeout` not taking into account, I'll have a look; Thanks.

**Comment by rustatian** [comment]
@Warxcell Is this all configuration? Might be you have a `supervisor` section?

**Comment by Warxcell** [comment]
This is whole conf:

```
version: "2.7"

server:
    command: "php /app/server.php"
    relay: "unix:///tmp/rr.sock"

http:
    address: ${HOST}:${PORT}
    pool:
        debug: ${RR_DEBUG}
        num_workers: ${RR_WORKERS}
        max_jobs: 0
        allocate_timeout: 120s
    middleware: [ "http_metrics", "static", "sendfile", "gzip" ]
    # Settings for "static" middleware (docs: https://roadrunner.dev/docs/http-static).
    static:
        dir: "/app/public/"
        forbid: [ ".php" ]
        calculate_etag: false
        weak: false

rpc:
    listen: tcp://127.0.0.1:6001

logs:
    mode: ${RR_LOGS}
    output: stderr

metrics:
    address: 0.0.0.0:8080
```

**Comment by rustatian** [comment]
Could you please try to use `relay: pipes`?

**Comment by Warxcell** [comment]
> Could you please try to use `relay: pipes`?

Yeah, with pipes it seems to work.

**Comment by rustatian** [comment]
Nice. I fixed the issue for the sockets/tcp. It will be later today in the `beta.2`.
