### ISSUE TITLE
[🐛 BUG]: Healthcheck returns 503 if http.pool.debug=true

### ISSUE THREAD

**Issue by Warxcell** [roadrunner-server/roadrunner#1235]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Healthcheck returns 503 if http.pool.debug=true

I would expect it to return 200 as well.

### Version (rr --version)

2.11.0-beta.2

### Relevant log output

```shell
no logs or whatsoever.
```

**Comment by rustatian** [comment]
Hey @Warxcell 👋 Healthchecks are not working in the debug mode since there are no workers in it.

**Comment by Warxcell** [comment]
Shouldn't they just return 200 always? The inconvenience comes from the fact that I'm using same configuration in ALL environments for readiness/liveness probes.

**Comment by rustatian** [comment]
Debug mode doesn't meant to be used anywhere except the local dev env. Status plugin doesn't know anything about the pool's debug mode. Plugins decoupled from each other.

**Comment by rustatian** [comment]
So, basically, status plugin checks the worker status. And if there are no workers at all, according to the plugin's logic - it returns 500.

**Comment by Warxcell** [comment]
Ok, I see. Thanks.
