### ISSUE TITLE
[🧹 CHORE]: Change timestamp formats for raw and production mode in log messages

### ISSUE THREAD

**Issue by ilsenem** [roadrunner-server/roadrunner#1236]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

For now I have some problems to parse logs RR produces.

Cases:

1. In `raw` mode HTTP log provides pretty useful information but timestamp is unparsable with standart log parsers because most of them use some kind of format parsing e.g. `%Y-%m-%dT%H:%M:%S`. There is no way to distinct epoch seconds from fractional part in this case 'cause timestamp is like `162352467344533226` (`start` field of log message). 
2. In `production` mode on the other hand, I have pretty formatted `1673456326.34535` value (`ts` field of every log message), but with `float` type. Situation may vary from one log parser to another but `fluentbit` for example does not recognize float as `%s.%L` format (epoch seconds and fractional part) 'cause it's type is not a `string`.

It could be easily mitigated by dropping timestamp parsing altogether but RR gives exact time and log parser only use time when log was received.

Dropping HTTP logs can be an answer too but it contains valuable information: elapsed time, status etc. Great addition to balancer access logs.

If there is a way to find the way around, it would be great.

**Comment by rustatian** [comment]
Hey @ilsenem 👋🏻 
Fair enought, I'll put this ticket to the 2.11 milestone, since it'd be easy fix that. Thanks 👍🏻

**Comment by rustatian** [comment]
done: https://github.com/roadrunner-server/logger/commit/de97180d319f41a1e707256f1b2f027a8b98ce55

```log
http log	{"status": 200, "method": "GET", "URI": "/", "remote_address": "127.0.0.1:57216", "read_bytes": 0, "write_bytes": 5242880, "start": **1660059505.8378034**, "elapsed": 25448417}
```

**Comment by rustatian** [comment]
The fix will be in the `beta.4` release (2022-08-11)
