### ISSUE TITLE
[🐛 BUG]: Building with velox 1.1.3 fails with roadrunner v2.11.1 as reference

### ISSUE THREAD

**Issue by zdraganov** [roadrunner-server/roadrunner#1294]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Trying to build roadrunner binary with velox 1.1.3 and roadrunner ref v2.11.1. Build fails with error of some type inconsistency.

Using the following velox.toml configuration for the build.
```
[velox]
build_args = [
    '-trimpath',
    '-ldflags',
    '-s -X github.com/roadrunner-server/roadrunner/v2/internal/meta.version=develop -X github.com/roadrunner-server/roadrunner/v2/internal/meta.buildTime=10:00:00']

[roadrunner]
ref = "v2.11.1"

[github]
    [github.token]
    token = "${RT_TOKEN}"

[log]
level = "debug"
mode = "development"
```

### Version (rr --version)

2.11.1

### Relevant log output

```shell
{"log": "# github.com/roadrunner-server/roadrunner/v2/internal/cli/workers\ninternal/cli/workers/render.go:33:17: cannot use workers[i].Pid (variable of type int64) as type int in argument to strconv.Itoa\ninternal/cli/workers/render.go:34:17: cannot use workers[i].Status (variable of type int64) as type string in argument to renderStatus\ninternal/cli/workers/render.go:35:26: workers[i].NumJobs undefined (type *process.State has no field or method NumJobs)\ninternal/cli/workers/render.go:58:17: cannot use workers[i].Pid (variable of type int64) as type int in argument to strconv.Itoa\n"
```

**Comment by rustatian** [comment]
Hey @zdraganov 👋🏻 
Could you please try to use the `ref="release/v2.11.2"` RR's branch? Unfortunately, I have to move some of the internals 😢 , thus the build fails.

**Comment by zdraganov** [comment]
Updated the ref in the velox.toml file and now get this error:

```
#22 0.121 2022-09-13T13:16:39.025Z      INFO    [GET ARCHIVE LINK]      {"owner": "roadrunner-server", "repository": "roadrunner", "encoding": "zip", "ref": "release/v2.11.2"}
#22 0.402 2022-09-13T13:16:39.305Z	INFO	[REQUESTING REPO]	{"url": "https://codeload.github.com/roadrunner-server/roadrunner/legacy.zip/refs/heads/release/v2.11.2"}
#22 0.402 2022-09-13T13:16:39.306Z	INFO	[FETCHING CONTENT]	{"url": "https://codeload.github.com/roadrunner-server/roadrunner/legacy.zip/refs/heads/release/v2.11.2"}
#22 0.899 2022-09-13T13:16:39.801Z	DEBUG	[FLUSHING DATA ON THE DISK]	{"path": "/tmp/roadrunner-server-release/v2.11.2.zip"}
#22 0.899 2022-09-13T13:16:39.802Z	FATAL	[DOWNLOAD TEMPLATE]	{"error": "open /tmp/roadrunner-server-release/v2.11.2.zip: no such file or directory"}
```

**Comment by zdraganov** [comment]
Just managed to make it working with this git tag - [343c5be](https://github.com/roadrunner-server/roadrunner/commit/343c5be977b1ca8d1cad0b821cf3cd38d49974ef) which has to be the latest in the mentioned release/v2.11.2 branch.

**Comment by rustatian** [comment]
Good, sorry for the inconvenience. I'll release `v2.11.2` on Thursday, so the problem should be gone.

**Comment by rustatian** [comment]
The problem with the `release/v2.11.2` branch is in the `/` in the branch name. It is recognized as a path, and I'll fix that.

**Comment by rustatian** [comment]
@zdraganov, Could you please try to use Velox `v1.1.4` with the branch name `release/v2.11.2`?

**Comment by zdraganov** [comment]
Yeah, looks like working with those versions! Great!
