### ISSUE TITLE
[💡 FEATURE REQUEST]: `buf` remote plugin for `protoc-gen-php-grpc`

### ISSUE THREAD

**Issue by rauanmayemir** [roadrunner-server/roadrunner#1297]
### Plugin

GRPC

### I have an idea!

I have an idea, listen to me!!

It would be nice to have a `protoc-gen-php-grpc` [remote plugin](https://docs.buf.build/bsr/remote-generation/plugin-example) on buf.build to simplify gRPC bindings generation.

I might take a stab at it later and send a PR.

**Comment by rustatian** [comment]
Hey @rauanmayemir 👋🏻 
Yeah, excellent proposal 👍🏻 I was waiting for at least **beta**, but it would be nice if you sent a PR (to the `gRPC` plugin).
