### ISSUE TITLE
[🐛 BUG]: Enabling PHP 8.1 opcache leads to ERROR

### ISSUE THREAD

**Issue by egonbraun** [roadrunner-server/roadrunner#1306]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

We are following the recommendations for Roadrunner in production described in [this](https://roadrunner.dev/docs/app-server-production/2.x/en) link and one of the things it asks us to do is to enable opcache in PHP. We have done it in this way:

```
[opcache]
opcache.enable_cli=1
opcache.jit_buffer_size=256M
```

However, turning this feature on is yielding the following error:

```
2022-09-25T10:03:28.632Z	ERROR	container/poller.go:16	vertex got an error	{"id": "http.Plugin", "error": "static_pool_allocate_workers: WorkerAllocate:\n\tgoridge_frame_receive: validation failed on the message sent to STDOUT, see: https://roadrunner.dev/docs/known-issues-stdout-crc/2.x/en, invalid message: \nWarning: JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0\n\u0013\u0001\u000c\u0000\u0000\u0000\ufffdG6C\u0000\u0000{\"pid\":5156}"}
```

We are using: 
- PHP 8.1
- Laravel 9.28.0
- Roadrunner 2.11.1
- Docker 20.10.17
- Amazon EC2 Linux (4.14.290-217.505.amzn2.x86_64)

Here is our Roadrunner configuration:

```
version: "2.7"

server:
  command: "php /app/vendor/bin/rr-worker start"
  relay: pipes
  user: www-data
  group: www-data

rpc:
  listen: tcp://:6001

http:
  address: 0.0.0.0:8000
  pool:
    num_workers: 0
    max_jobs: 64
    supervisor:
      exec_ttl: 300s

logs:
  mode: production
  level: error
  encoding: json

status:
  address: localhost:2114
```

### Version (rr --version)

2.11.1

### Relevant log output

```shell
2022-09-25T10:03:28.632Z	ERROR	container/poller.go:16	vertex got an error	{"id": "http.Plugin", "error": "static_pool_allocate_workers: WorkerAllocate:\n\tgoridge_frame_receive: validation failed on the message sent to STDOUT, see: https://roadrunner.dev/docs/known-issues-stdout-crc/2.x/en, invalid message: \nWarning: JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0\n\u0013\u0001\u000c\u0000\u0000\u0000\ufffdG6C\u0000\u0000{\"pid\":5156}"}

github.com/roadrunner-server/endure/pkg/container.(*Endure).poll.func1
 	github.com/roadrunner-server/endure@v1.4.5/pkg/container/poller.go:16
 error: static_pool_allocate_workers: WorkerAllocate:
 	goridge_frame_receive: validation failed on the message sent to STDOUT, see: https://roadrunner.dev/docs/known-issues-stdout-crc/2.x/en, invalid message:
 Warning: JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0
                           G6C{"pid":5156}
```

**Comment by rustatian** [comment]
Hey @egonbraun 👋🏻 
The `STDOUT` is reserved for communication between RR and PHP workers by the defined protocol. When RR receives some unknown message, it fails.
The message `Warning: JIT is incompatible with third party extensions that...` is from PHP; you should turn off the warnings in the `php.ini` file.

**Comment by egonbraun** [comment]
True! That's why it is crashing and I will be able to fix it following the tips in the link.

I was more worried about the warning messages, is this warning a problem for Roadrunner as well? Is it safe to ignore it?

**Comment by rustatian** [comment]
Yeah, you may safely ignore it (if it's safe for you to neglect this warning in PHP).

**Comment by egonbraun** [comment]
Thanks, @rustatian !

**Comment by rustatian** [comment]
Also, I saw in your config: `max_jobs: 64`. You may also remove this option. This option should be used for the apps which leak memory to restart the worker (in your case) for every 64 requests.

**Comment by rustatian** [comment]
I'll also add your case to the docs. Thank you 👍🏻

**Comment by egonbraun** [comment]
One more piece of information that might help someone, the above message is generated by XDebug. So make sure you do not enable XDebug together with opcache.
