### ISSUE TITLE
[🐛 BUG]: woff2 fonts are detecting with the wrong mime type

### ISSUE THREAD

**Issue by masterjus** [roadrunner-server/roadrunner#1321]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

We're using the Static Midleware to proxy static files. During the test we've found that .woff2 fonts are respond with the "content-type: text/plain" header.

Expected: 
The Content-type header is font/woff2;

### Version (rr --version)

2.11.4

**Comment by rustatian** [comment]
Hey @masterjus 👋🏻 
Yeah, that's weird; I'll double-check that case and release a fix.

**Comment by masterjus** [comment]
In addition I'd add that fonts are preloading with the meta tag `link`.

`<link rel="preload" href="/fonts/static/Lato-Regular.woff2" as="font" crossorigin="anonymous">`

**Comment by rustatian** [comment]
@masterjus, Could you please provide some test cases to reproduce this behavior? (`.rr.yaml`,sample of the request with woff2, etc).

**Comment by rustatian** [comment]
Friendly ping @masterjus

**Comment by rustatian** [comment]
Friendly ping2 @masterjus -> https://github.com/roadrunner-server/roadrunner/issues/1321#issuecomment-1295927373

**Comment by eboboshka** [comment]
@masterjus I think you should check how your OS identifies files where the files are stored.
```file --mime-type /path/file.woff2```

Maybe your RR is running in a Docker container that doesn't have a complete mime list. Check the file `/etc/mime.types` (alternatively, you can create it and test it again)
RFC 4288 (for example - https://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types)

**Comment by rustatian** [comment]
Closed due to inactivity.
@masterjus Feel free to provide a reproducible sample to reopen the issue.
