### ISSUE TITLE
[💡 FEATURE REQUEST]: RPC method to manage process num

### ISSUE THREAD

**Issue by butschster** [roadrunner-server/roadrunner#1345]
### I have an idea!

I have an idea, listen to me!!

It would be great to have the ability to  manage process num by RPC. Something like

```php
$rpc->call('http.AddProcess');
$rpc->call('http.KillProcess');

$rpc->call('jobs.AddProcess');
$rpc->call('jobs.KillProcess');
```

**Comment by rustatian** [comment]
dup: https://github.com/roadrunner-server/roadrunner/issues/97
