### ISSUE TITLE
[🐛 BUG]: Jobs worker doesn't have statusStr in RPC

### ISSUE THREAD

**Issue by butschster** [roadrunner-server/roadrunner#1346]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

When I get inforamation about Jobs plugin workers there isn't information about worker status in string format

### Version (rr --version)

2.11.4

### How to reproduce the issue?

Just get information about workers by RPC

**Comment by rustatian** [comment]
We have a common mechanism to get info about workers (http, jobs, grpc, etc). Specifically to the jobs, here is the method:
https://github.com/roadrunner-server/jobs/blob/master/plugin.go#L270

And here, you may see the output: `StatusStr` = `ready`
![image](https://user-images.githubusercontent.com/8040338/199266294-a9cf5aee-2716-4d9c-a5ae-0c3eeccf1c05.png)
