### ISSUE TITLE
[💡 FEATURE REQUEST]: Add syntax validation of .rr.yaml on server startup

### ISSUE THREAD

**Issue by andrey-tech** [roadrunner-server/roadrunner#1355]
### Plugin

JOBS

### I have an idea!

Please, add full syntax validation of config file `.rr.yaml` on server startup. Without this feature, server behavior may be unpredictable.

For example, if syntax error (typo) exists in the first line of `.rr.yaml`:
```yaml
durabversion: "2.7"
```
then no errors are occurs and no warnings in the log. AMQP driver successfully connects to correct RabbitMQ server, specified by parameter `addr:` of file  `.rr.yaml`, but driver connects to incorrect default queue `default` (parameter `queue:` is ignored).

**Comment by rustatian** [comment]
Hey @andrey-tech 👋🏻 
RR has a backward-compatible configuration. That means if you run RR version 2.11.4 on the configuration without the version, RR assumes you're running an unversioned configuration version (was previously) and automatically updates your configuration.

For example: `durabversion: "2.7"`. RR will not read this key in any way and assumes you're running an old configuration version.

Also, `queue`, `addr`, and other args have default values (you may have a look and the `rr.yaml` in the repo root). If you provided an address like `tcp://foo.bar`. It's a valid address (imagine you're running RR in the docker and have a container with that name (DNS))

Thus, I'm not sure what exactly RR should validate.

EDIT: RR validates that you're provided a valid `yaml`.

**Comment by andrey-tech** [comment]
Hi @rustatian 

I would like to have `.rr.yaml` file specification similar to Docker [Compose specification](https://docs.docker.com/compose/compose-file/).

For example, fragment from [Compose specification](https://docs.docker.com/compose/compose-file/):
```txt
Version top-level element

Compose implementations SHOULD validate whether they can fully parse the Compose file.
If some fields are unknown, typically because the Compose file was written with fields defined 
by a newer version of the specification, Compose implementations SHOULD warn the user.
```

So, if I run Docker Compose with syntax error (typo) in first line of Compose yaml-file `durabversion: "2.7"`, then I got an error: `(root) Additional property durabversion is not allowed `. I would like to have same predictable behavior from RR.

**Comment by rustatian** [comment]
Yeah, this would be nice to have such a document. We have a RR2 schema in the [schemastore](https://cdn.jsdelivr.net/gh/roadrunner-server/roadrunner@latest/schemas/config/2.0.schema.json) as the first step to the formal specifications. 
I would appreciate a PR or any help in that direction.

**Comment by rustatian** [comment]
Thanks for the FR @andrey-tech 👍🏻 

1. RR configuration plugin validates YAML.
2. All plugins validate their configuration and report errors if you use an incorrect address or for example instead of int you use string.
3. Additionally you may also validate your schema for correctness with the following tool: https://github.com/roadrunner-server/roadrunner/tree/master/schemas
