### ISSUE TITLE
[💡 FEATURE REQUEST]: Add ability to publish jobs to another queues not specified in project ppelines

### ISSUE THREAD

**Issue by iborysenko** [roadrunner-server/roadrunner#1364]
### Plugin

JOBS

### I have an idea!

I have an idea, listen to me!!
Add ability to publish message to jobs with specified routing_key.
I'm trying to use RR jobs to build cross-service Message-Bus communication, but I can't dispatch job to another queue outside specified project pipelines. 

Or maybe I don't understand something ?

**Comment by rustatian** [comment]
Hey @iborysenko 👋🏻 
You can create a pipeline with a needed routing key, do not consume it, and push jobs to it.

**Comment by iborysenko** [comment]
thanks @rustatian I checked it, everything works fine. 
I think this point must be documented.

**Comment by rustatian** [comment]
Yeah, you're right; I'll add this ticket to the docs TODOs for v2.12.0, thanks 👍🏻

**Comment by iborysenko** [comment]
It works, but bit uncomfortable.
For example we have two services
1. `User Service` need to dispatch job like `user-created` 
2. `Balance Service` need to process `user-created` job and create balance for this user


Here two solutions to dispatch:
1. Define in `user-service` pipeline the same as in `balance-service` and dispatch jobs directly to external service queue
2.
 a) Define `user-service` queue and process it without any logic `$task->complete()`.
 b) Define `balance-service` queue and process it with balance creation logic

First solution is bad because one service know about another service queues, 
Second in case when `user-service` no need to process own events will dispatch events and complete it in infinite loop

What do you think @rustatian ?

**Comment by rustatian** [comment]
When creating a pipeline, you're not forced to process its jobs. 
You may create pipelines dynamically from the PHP OR via the configuration. 
So, if you wanted to only push the jobs via the `user-service` pipeline, do not add this pipeline to the [list of consumers](https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L1625).

If I understand correctly, `user-service` (and the associated pipeline) will be responsible to PUSH the JOBS (you don't need smt like `task->complete()`).

`balance-service` will receive the jobs pushed to the `user-service` pipeline.

**Comment by iborysenko** [comment]
@rustatian 
Yes, but I always need to specify queue, and I can't dispatch job directly to exchange with `routing-key`.

For example `user-service` dispatch events to exchange `user-service.event` with different routing keys like `user.created|user.updated|user.suspended`, etc.
Not to default queue, not for any other queues just exchange & routing-key. 

Like this, but without queue declaration and binding to exchange (but I think this is impossible right now)
https://github.com/roadrunner-server/amqp/blob/f943a043d1633dae6f1e377e0f990f712a648e1f/amqpjobs/consumer.go#L525

**Comment by rustatian** [comment]
@iborysenko 
Yeah, but JOB is queue agnostic and contains no queue-specific data. I understand your point; As an option, you may also push the JOBS from any external driver from any language. You may even push just a payload (like a byte array), specify `consume_all: true` in the pipeline's options, and RR will create a JOB by itself and provide it for the worker.

---

I'm open to proposals, you may create a feature-request ticket, and describe your case in detail, and if the community support it, I'll immediately implement this for all our users 😃.

**Comment by iborysenko** [comment]
Fully resolved in https://github.com/spiral/roadrunner-jobs/issues/30
@rustatian Thanks
