### ISSUE TITLE
[💡 FEATURE REQUEST]: kafka plugin sasl auth

### ISSUE THREAD

**Issue by VadymBerezdetskyi** [roadrunner-server/roadrunner#1392]
### Plugin

JOBS

### I have an idea!

Implement sasl authorization for kafka plugin

**Comment by rustatian** [comment]
Hey @VadymBerezdetskyi 👋🏻 
Thanks for the contribution, planned for the `2023.01` release.

**Comment by rustatian** [comment]
Hey @VadymBerezdetskyi 👋🏻 

What type of SASL auth do you use? I mean, just plain username and pass?

**Comment by VadymBerezdetskyi** [comment]
Hi!
it's sasl_plaintext, scram-sha-512 with username and password.

вт, 17 янв. 2023 г. в 16:56, Valery Piashchynski ***@***.***>:

**Comment by rustatian** [comment]
Done: https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L1547 (will be available to test in the next beta).
