### ISSUE TITLE
[💡 FEATURE REQUEST]: Driver in the queue task

### ISSUE THREAD

**Issue by msmakouz** [roadrunner-server/roadrunner#1431]
### Plugin

JOBS

### I have an idea!

When RR sends a task to an application, the task contains **body**, **header**, **eos**.

The header array contains information about the job: **id**, **job**, **pipeline**...
It would be great to have the **driver** in the header array. Tasks from some drivers may have additional information. For example, Kafka driver tasks additionally receive fields in the header: topic, partition, offset. It would be great to have a driver value in the received data to understand what data structure needs to be processed on the PHP side. Thanks.

**Comment by rustatian** [comment]
RR will return the following driver's names:
1. `memory`
2. `kafka`
3. `amqp`
4. `beanstalk`
5. `sqs`
6. `nats`
7. `boltdb`

**Comment by rustatian** [comment]
Done
