### ISSUE TITLE
[💡 FEATURE REQUEST]: Ability to set AMQP behavior/management params

### ISSUE THREAD

**Issue by codercms** [roadrunner-server/roadrunner#1432]
### Plugin

JOBS

### I have an idea!

I trying to listen for AMQP queue and faced following problems:
* Is it possible to set AMQP consumer name?
 There are many consumers and it would be great to set the name of consumer, e.g. `<service-name>-<host name>`
* AMQP plugin is always trying to create exchange/queue
Usually queue workers doesn't have access to modify RabbitMQ exchange/queue schema by security reasons.
Is there any way to prevent a queue worker from creating an exchange/queue and have it just listen?

**Comment by rustatian** [comment]
Hey @codercms 👋🏻 

1. Not at the moment, but adding a configuration option is easy. I'll add the new configuration options.
2. Not create, but check if it exists (and only if not - create). This is an idempotent operation (if the exchange exists) to check that configuration fits the exchange configuration. In the latest version, if you do not consume from the queue, RR will not try to check the queue and create it if it doesn't exist. But if you did consume, RR has to check the queue to be aligned with that declared in the configuration. This is also an idempotent operation.
