### ISSUE TITLE
[🧹 CHORE]: Jobs, amqp,  add redialTimeout to confuguration reference docummentation  

### ISSUE THREAD

**Issue by iborysenko** [roadrunner-server/roadrunner#1476]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

[This parameter is useful](https://github.com/roadrunner-server/amqp/blob/master/amqpjobs/driver.go#L245)
But not exists in the full configuration reference

**Comment by rustatian** [comment]
Please, read the docs first: https://roadrunner.dev/docs/plugins-jobs/2.x/en#amqp-driver

![image](https://user-images.githubusercontent.com/8040338/221163211-73a6b8a0-c2e9-46d4-ba2a-eba9e90f2c28.png)
