### ISSUE TITLE
[🐛 BUG]: Unable to install v2023 RoadRunner via Composer

### ISSUE THREAD

**Issue by monkenWu** [roadrunner-server/roadrunner#1540]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Compared to the composer.json of v2.12.3, the composer.json of v2023 does not contain any dependency libraries "spiral/roadrunner-worker", "spiral/roadrunner-cli" and "spiral/roadrunner-http" .

This will prevent RoadRunner from being installed using the installation-via-composer mentioned in the README.

### Version (rr --version)

2023.1.0

### How to reproduce the issue?

When installing with Composer.
```
composer require spiral/roadrunner:v2023.1.0 nyholm/psr7
```

**Comment by rustatian** [comment]
Hey @monkenWu 👋🏻 
Yes, you're right. Starting with `v2023`, RoadRunner is really a meta package from a PHP point of view.
We will update the Readme shortly.
