### ISSUE TITLE
[🐛 BUG]: Double config marshaling in the HTTP plugin

### ISSUE THREAD

**Issue by WagnerPMC** [roadrunner-server/roadrunner#1541]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

On lines 93 and 99 there is a double marshaling of the configuration. See for yourself:
https://github.com/roadrunner-server/http/blob/dfb87ef87e65e948209eb25d7bbbb3232494b97a/plugin.go#L93
https://github.com/roadrunner-server/http/blob/dfb87ef87e65e948209eb25d7bbbb3232494b97a/plugin.go#L99

### Version (rr --version)

latest

PR: https://github.com/roadrunner-server/http/pull/118

**Comment by rustatian** [comment]
Hey @WagnerPMC 👋🏻 
Thanks for the report, good catch. Hovewer, according to our [policy](https://github.com/roadrunner-server/roadrunner/blob/master/CODE_OF_CONDUCT.md) we cannot accept issues from you.
