### ISSUE TITLE
[🐛 BUG]: TestCommandWorkingDir fails while packaging in a sandboxed environment

### ISSUE THREAD

**Issue by shyim** [roadrunner-server/roadrunner#1545]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

```
ok      github.com/roadrunner-server/roadrunner/v2023/container 0.333s
--- FAIL: TestCommandWorkingDir (0.00s)
    root_test.go:161:
                Error Trace:    /private/tmp/nix-build-roadrunner-2023.1.0.drv-0/source/internal/cli/root_test.go:161
                Error:          Not equal:
                                expected: "/tmp"
                                actual  : "/private/tmp/nix-build-roadrunner-2023.1.0.drv-0"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -/tmp
                                +/private/tmp/nix-build-roadrunner-2023.1.0.drv-0
                Test:           TestCommandWorkingDir
```

### Version (rr --version)

2023.1.0

### How to reproduce the issue?

Run in a environment where the Temp folder is not /tmp (set TMPDIR/TEMPDIR)

**Comment by rustatian** [comment]
Hey @shyim 👋🏻 
Yeah, we should use `os.TempDir` in the `assert`, instead of `/tmp`. Will fix that, thanks 👍🏻

**Comment by rustatian** [comment]
fixed in: https://github.com/roadrunner-server/roadrunner/commit/7e961965b6e53efaf3e6a56da2ac06794818d200

**Comment by shyim** [comment]
thank you for the fast fix. Will package soon Roadrunner for Nix :)

**Comment by rustatian** [comment]
> thank you for the fast fix. Will package soon Roadrunner for Nix :)

This is super cool, I used to use Nix :)
I also wanted to make an AUR/Community package for ArchLinux...
