### ISSUE TITLE
[🧹 CHORE]:  Mention about the removal of the `reload` plugin

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/roadrunner#1549]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

Hello. Can you mention  about remove `reload` plugin  here please

https://roadrunner.dev/docs/plugins-config/2023.x/en#v30-configuration

**Comment by rustatian** [comment]
Done: https://github.com/roadrunner-server/roadrunner-docs/commit/83eb455de4be25d653938c8ac76754a308cce0b6
