### ISSUE TITLE
[💡 FEATURE REQUEST]: Support for non-JSON payload formats and non-UTF8 symbols in task payload

### ISSUE THREAD

**Issue by butschster** [roadrunner-server/roadrunner#1556]
### Plugin

JOBS

### I have an idea!

The current implementation of the RoadRunner jobs plugin only allows for JSON payload formats and UTF8 symbols in the task payload. However, there may be cases where users need to send payloads in other formats, such as protobuf or plain strings containing non-UTF8 symbols.

I would like to request a feature that allows for support of non-JSON payload formats and non-UTF8 symbols in the task payload. 

- [x] AMQP
- [x] Beanstalk
- [x] In-memory
- [x] BoltDB
- [x] SQS
- [x] NATS
- [x] Kafka

**Comment by rustatian** [comment]
Hey @butschster 👋🏻 
As a first step, PHP worker should support non-JSON encoded payloads (currently the codec used for the goridge is JSON (this is not related to the queue messages)). For the JOBS it would be this proto: https://github.com/roadrunner-server/api/blob/master/jobs/v1/jobs.proto#L25
Once this is supported, I would be able to send all payloads encoded with the proto codec in binary format.

**Comment by rustatian** [comment]
Done @butschster 🥳 
Will be included into the next beta release ❤
