### ISSUE TITLE
[🧹 CHORE]: Possible typo in AMQP-driver property named `multiple_ack`

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1565]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

Let's find the [multiple_a**c**k](https://github.com/search?q=repo%3Aroadrunner-server%2Famqp+multiple_ack&type=code) param - there are no results.

Let's find the "multiple_a**s**k" [roadrunner-server/amqp](https://github.com/search?q=repo%3Aroadrunner-server%2Famqp+multiple_ask&type=code) - i found mapping multiple_a**s**k => MultipleA**c**k.

But in AMQP config we have only [multiple_a**c**k](https://github.com/search?q=repo%3Aroadrunner-server%2Froadrunner%20multiple_ack&type=code) param.

---

Additional: check the tests: https://github.com/roadrunner-server/rr-e2e-tests/blob/master/plugins/jobs/amqp/jobs_amqp_test.go

**Comment by rustatian** [comment]
Hey @embargo2710 👋🏻 
Yeah, this is def typo. Will fix that, thanks 👍🏻

**Comment by Kaspiman** [comment]
@rustatian 
Since we met in this issue, can you add a more understandable description for the "multiple_ack" parameter? 

> multiple_ack - this delivery, along with all prior unacknowledged deliveries on the same channel, will be acknowledged. This feature is beneficial for batch processing of deliveries and is applicable only for Ack, not for Nack.

what is the "this delivery" and what could heapen when multiple_ack is true? At what moment of Jobs/task lifecycle can this happen?

**Comment by rustatian** [comment]
Delivery is the messages that are delivered through the queue. This is the default rabbitmq term. Communication with the rabbitmq broker is done through the channels. So, for example, if you have the 10 messages that are being processed by the workers, and you use `multiple_ack=true`, then when the first message (JOB) is processed, it'll auto-acknowledge all the previous messages (Deliveries): https://www.rabbitmq.com/confirms.html#consumer-acks-multiple-parameter
