### ISSUE TITLE
[💡 FEATURE REQUEST]: Add support for SCRAM-SHA-* kafka SASL mechanism

### ISSUE THREAD

**Issue by Azomas** [roadrunner-server/roadrunner#1601]
### Plugin

None

### I have an idea!

Hi, everyone.
Thanks a lot for your work!

I suggest adding support for SCRAM-SHA-* SASL mechanism to roadrunner-server/kafka driver.
There is already support for PLAIN mechanism based on this package https://github.com/twmb/franz-go/blob/master/pkg/sasl/plain/plain.go.
In order to add SCRAM-SHA-* support in roadrunner I suggest using the same package's feature - https://github.com/twmb/franz-go/blob/master/pkg/sasl/scram/scram.go

**Comment by rustatian** [comment]
Hey @Azomas 👋🏻 Thanks for the feature request 👍🏻 
I'll try to address it to the `v2023.2.0` release ⚡

**Comment by rustatian** [comment]
Done: https://github.com/roadrunner-server/kafka/pull/140
I'm going to merge that next week, will be in the first `v2023.2.0` beta release on Thursday.
