### ISSUE TITLE
[💡 FEATURE REQUEST]: configure each process command in service

### ISSUE THREAD

**Issue by zakharov-ilia** [roadrunner-server/roadrunner#1606]
### Plugin

Service

Hi!

In classic supervisor we can use the following syntax:

```
numprocs=5
php bin/console messenger:consume --queues=some_queue_name_%(process_num)02d
```

Where %(process_num)02d - number of current process (0-4 for 5 processes).

How about the idea of implementing such a thing here in the service plugin? So that we can specify command for each service process.

**Comment by rustatian** [comment]
Hey @zakharov-ilia 👋🏻 
You can use any command you want per service, RR does not limit you in this area (`command` configuration option). Or did you mean something else?

**Comment by zakharov-ilia** [comment]
Not really about that.

Let's say we set the number of processes as 5 (process_num=5).

I want each of them to start with a different command, for example:

php bin/console messenger:consume --queues=some_queue_name_0
php bin/console messenger:consume --queues=some_queue_name_1
php bin/console messenger:consume --queues=some_queue_name_2
php bin/console messenger:consume --queues=some_queue_name_3
php bin/console messenger:consume --queues=some_queue_name_4

Yes, if there are only 5 processes, I can just use different services.
But if there are 100, it's less convenient.

Here is an example of the supervisor's analogue - http://supervisord.org/configuration.html (search text "%(process_num)02" on the page)

**Comment by rustatian** [comment]
You can declare services on the fly from the PHP using any command you want forming the resulting string on the fly as well.


EDIT: https://github.com/roadrunner-php/services#create-a-new-service

**Comment by zakharov-ilia** [comment]
It looks great, thank you!
But, I can't find an example of how to most correctly implement service creation from PHP, as it needs to be done every time the roadrunner starts up. Can you suggest or link to examples?
Thanks in advance, the tool is great.

**Comment by rustatian** [comment]
You're very welcome 😃 

You may found more examples with API here: https://github.com/roadrunner-php/services
But generally, you may create let's say `master` service (`php` script) which will create all other services you need. RR sends SIGINT/SIGTERM signals when it's stopped to stop the underlying processes, so you may catch these signals and gracefully terminate your services.
Also, you may create services from any worker you use (like `http`, `gRPC`, etc). One note, that `service` script might be anyting you want, not nessesary a RR worker (with `while (true) loop`).

**Comment by zakharov-ilia** [comment]
Yes, I understand, but I don't want to make up my own supervisor.

Looked at the realization of this plugin (service) - in general it's not hard to replace some parameters by some regular expression (perhaps someone will be interested in this in the future).

Thanks!
