### ISSUE TITLE
[🐛 BUG]: Session doesn not work with Symfony

### ISSUE THREAD

**Issue by speller** [roadrunner-server/roadrunner#1619]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Sessions in my Symfony are recreated on every request.

### Version (rr --version)

2.12.2

### How to reproduce the issue?

Not sure how to reproduce it. 

Environment: local HTTP
Symfony version: 6.2.5
baldinof/roadrunner-bundle: 2.2.4

In the `\Baldinof\RoadRunnerBundle\Http\KernelHandler::handle()` method, the request contains the session id cookie:

<img width="369" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/1829515/77182a0f-2905-4707-b900-3bae1741de02">

But there's no `$_COOKIE` array

<img width="169" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/1829515/33bc0820-b09c-445c-93cb-e3c7199e5c0d">

So when Symfony tries to start a session in `\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage::start()`, it tries to get the session id value from `$_COOKIE` and gets nothing, creating a new session. How to fix this?

I found only this relevant issue #18 but it's quite old and closed.

**Comment by rustatian** [comment]
Hey @speller 👋🏻 
There are no superglobals in the RR. HTTP plugin supports PSR-7 standard. To get the cookies, you can use `getCookieParams` on the RR request.

**Comment by rustatian** [comment]
Converting into a discussion, since this is not a bug.
