### ISSUE TITLE
[🐛 BUG]: Services manager wrong processNum from php client

### ISSUE THREAD

**Issue by asanikovich** [roadrunner-server/roadrunner#1621]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I tries by RoadRunner Service Plugin docs https://roadrunner.dev/docs/plugins-service/current/en to run process in 3 copies from php client (code below).
But it creates only 1 process.
In the RPC I can see that 3 are passing.

### Version (rr --version)

rr version 2023.1.5 (build time: 2023-06-08T14:45:04+0000, go1.20.5), OS: linux, arch: amd64
Php libraries:
       "spiral/roadrunner-cli": "2.5.0",
        "spiral/roadrunner-http": "3.0.1",
        "spiral/roadrunner-kv": "4.0.0",
        "spiral/roadrunner-metrics": "3.0.0",
        "spiral/roadrunner-services": "2.0.0",

### How to reproduce the issue?

```php
        $result = $this->manager->create(
            name: $commandBase,
            command: sprintf('php artisan %s', $command),
            processNum: 3,
            remainAfterExit: (bool)$autoRestart,
            restartSec: 1
        );
```

**Comment by rustatian** [comment]
Hey @asanikovich 👋🏻 
How you determine, that only 1 process fired?

**Comment by asanikovich** [comment]
I see in process manager (top) that only 1 run process running.

**Comment by rustatian** [comment]
Ok, got u, let me verify that

**Comment by rustatian** [comment]
You're right @asanikovich 👍🏻 Bug confirmed. Will be fixed and released in the `2023.2.0` release.

**Comment by rustatian** [comment]
As a temporary workaround, you can use `.rr.yaml` configuration to define the required number of processes. Seems to be an RPC service creation bug only.

**Comment by asanikovich** [comment]
I need to dynamically run processes from RPC

**Comment by rustatian** [comment]
Got u, then please wait for `2023.2.0`, scheduled to release in early July.

**Comment by asanikovich** [comment]
Why there is no "service_name_in_log" parameter to run service process from rpc?

**Comment by rustatian** [comment]
Feel free to create a feature request to add that option in the RPC transport as well 😃
