### ISSUE TITLE
[💡 FEATURE REQUEST]: Service plugin add support stop_wait_secs (graceful termination)

### ISSUE THREAD

**Issue by asanikovich** [roadrunner-server/roadrunner#1628]
### Plugin

Service

### I have an idea!

Please add to service plugin configuration next parameter:
**stop_wait_secs** 
You have default 5s to wait until process finished after sending SIGINT to process from RR.
It will be good to support custom **stop_wait_secs** to control termination flow (graceful termination).

Please add to RPC commutation with service plugin next parameters (to support define from PHP):

- service_name_in_logs - to support define from PHP
- stop_wait_secs - describe above

[Discussion](https://github.com/orgs/roadrunner-server/discussions/1627)

**Comment by rustatian** [comment]
Hey @asanikovich 👋🏻 
I will try to implement this for `2023.2.0`, but we only have 2 weeks until the release...
Since our options are similar to the `systemd` unit file options, `stop_wait_secs` would be `TimeoutStopSec` -> `timeout_stop_sec`.

**Comment by asanikovich** [comment]
What's mean global parameter `grace_period: 30s` (defined at line https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L2169)?

**Comment by asanikovich** [comment]
@rustatian What's mean global parameter `grace_period: 30s` (defined at line https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L2169)?

**Comment by rustatian** [comment]
This is the general RR graceful shutdown timeout. When it expires, RR will exit regardless of the fact that some plugin is still in the middle of shutdown.
