### ISSUE TITLE
[🐛 BUG]: Segfault when sending message via nats-cli

### ISSUE THREAD

**Issue by KernelMrex** [roadrunner-server/roadrunner#1650]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I have got segfault in RoadRunner container when sending data like this
```
nats -s 127.0.0.1:4222 pub default "test 2345"
```

Error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x126f3c3]

goroutine 48 [running]:
github.com/roadrunner-server/nats/v4/natsjobs.(*Driver).listenerStart.func1()
        github.com/roadrunner-server/nats/v4@v4.2.9/natsjobs/listener.go:58 +0x3e3
created by github.com/roadrunner-server/nats/v4/natsjobs.(*Driver).listenerStart
        github.com/roadrunner-server/nats/v4@v4.2.9/natsjobs/listener.go:32 +0x56     
```

### Version (rr --version)

rr version 2023.1.5 (build time: 2023-06-08T14:45:06+0000, go1.20.4), OS: linux, arch: amd64

### How to reproduce the issue?

Install nats-cli tool from via `go install github.com/nats-io/natscli/nats@latest`

```
nats -s 127.0.0.1:4222 pub default "test 2345"
```

**Comment by rustatian** [comment]
Hey @KernelMrex 👋🏻 
Yeah, I can confirm that the bug exists. Planned for the `2023.2.1` bugfix release.

**Comment by rustatian** [comment]
BTW, you may use `consume_all: true` pipeline option to bypass this error. This option should be used if you send non json encoded data via console or [any third party sender](https://roadrunner.dev/docs/queues-nats/current/en#consume-all)
