### ISSUE TITLE
[💡 FEATURE REQUEST]: Notify service manager about start-up completion and other service status changes

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1654]
### Plugin

None

### I have an idea!

i'm using Roadrunner + Systemd and having a little restart problems. Command `systemctl restart roadrunner` with [default unit](https://roadrunner.dev/docs/app-server-systemd/current) does not guarantee server readiness.

Comes to mind to use a script and check port availability with [wait-for-it.sh](https://github.com/vishnubob/wait-for-it) or something else.

Maybe we can add come signals like [sd_notify](https://manpages.org/sd_notify/3)? People already [has](https://github.com/coreos/go-systemd/tree/main) library for that.

EDIT:
Some docs: 
1. https://www.freedesktop.org/software/systemd/man/systemd.service.html#NotifyAccess=
2. https://www.freedesktop.org/software/systemd/man/sd_notify.html#

**Comment by rustatian** [comment]
Hey @Kaspiman 👋🏻 
Yeah, nice idea. I'll look into that, thanks 👍🏻

**Comment by rustatian** [comment]
To test the feature, feel free to download build artifacts here: https://github.com/roadrunner-server/roadrunner/actions/runs/5867205849
