### ISSUE TITLE
[💡 FEATURE REQUEST]: Dynamic Workers Scaling via RPC

### ISSUE THREAD

**Issue by butschster** [roadrunner-server/roadrunner#1728]
### Plugin

JOBS

### Hey there, folks! 😄

RoadRunner offers multiple plugins like `http`, `jobs`, and `grpc` that allow the deployment of workers pools with predefined numbers in the configuration. 

```yaml
version: "3"

http:
  pool:
    num_workers: 0
```

At present, if there's a need to modify the number of workers, one must stop RoadRunner, modify the configuration, and then start the server again.

There exists an RPC method, `informer.Workers`, which lets users query the current number of workers for a given plugin.

```php
$result = $rpc->call('informer.Workers', 'http');
var_dump($result['workers']); 
```

## Proposal:

To enhance the operational flexibility and adaptability of RoadRunner, I propose the introduction of two new RPC methods:

1. `server.AddWorker(plugin, number)`
2. `server.RemoveWorker(plugin, number)`

### Benefits:

1. **Dynamic Scaling:** By introducing these methods, we provide a way for dynamically increasing or decreasing the number of workers for a specific plugin. This will prove invaluable for system administrators, especially in scenarios where traffic or load is unpredictable.

3. **Efficiency During Peak Hours:** For plugins like `http` or `grpc`, the ability to dynamically scale workers can be used to manage increased traffic during peak hours. This ensures optimal utilization of resources and smoother user experience.

4. **Adaptable Job Workers:** In the context of the `jobs` plugin, if there's a significant number of tasks in the queue, workers can be scaled up to process the load faster. Conversely, during periods of low activity, the number of workers can be reduced to free up system resources.

---

The addition of these methods would greatly improve the flexibility of RoadRunner, making it even more attractive for applications that require on-the-fly adaptability.

### 👍👍👍👍  If you like my proposal and would like to see it implemented, please give this issue a thumbs up! Your feedback plays a crucial role in getting attention from the RoadRunner maintainers.

**Comment by rustatian** [comment]
Hey @butschster 👋🏻 
Such a detailed FR, good job ❤️
