### ISSUE TITLE
[🐛 BUG]: serve_http: invalid semicolon separator in query

### ISSUE THREAD

**Issue by xieruidong521** [roadrunner-server/roadrunner#1733]
### No duplicates 🥲.

- [x] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

### Version (rr --version)

rr version 2.12.3 (build time: 2023-02-16T13:08:35+0000, go1.20), OS: windows, arch: amd64

### How to reproduce the issue?

请求网址:
http://sophia.test.com/storage/public:MjAyMy8wOS8yMy9JTVZLWHBLUDFXcGJaSFlEODIxZHJqVjlmSVBNZHNpMWgxOEhEWFlZSURHTE9WNzJ0WUhPc00wdlJHNDQzckdtLmpwZWc=?expires=1695433210&noStr=%242y%2410%24M9IgtLXD983gFt1%2FICXw9uNwXa4Yjy6cKjvsfKZBlYHd0n.rk630q&signature=0951ba3f9e1ac743e51cf4950dff15a9be10bb5ec058d9e6fe68e6482321622c
请求方法:
PUT
状态代码:
500 Internal Server Error

response:
serve_http: invalid semicolon separator in query
![image](https://github.com/roadrunner-server/roadrunner/assets/28883857/fefdd919-a361-4dc9-b3ee-fc5adbdb9dea)
![image](https://github.com/roadrunner-server/roadrunner/assets/28883857/655ed0e1-a460-43c3-a959-78721104d884)

**Comment by xieruidong521** [comment]
```nginx
server {
	listen 80;
        server_name  ~^(?<subdomain>.+).test.com;
        root D:\www\$subdomain\public;
	 
		index index.php index.html index.htm;
	 
		charset utf-8;
	 
		location /index.php {
			try_files /not_exists @octane;
		}
	 
		location / {
			try_files $uri $uri/ @octane;
		}
	 
		location = /favicon.ico { access_log off; log_not_found off; }
		location = /robots.txt  { access_log off; log_not_found off; }
	 
		access_log off;
	 
		error_page 404 /index.php;
	 
		location @octane {
			set $suffix "";
			if ($uri = /index.php) {
				set $suffix ?$query_string;
			}
			proxy_http_version 1.1;
			proxy_set_header Host $http_host;
			proxy_set_header Scheme $scheme;
			proxy_set_header SERVER_PORT $server_port;
			proxy_set_header REMOTE_ADDR $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection $connection_upgrade;
	 
			proxy_pass http://127.0.0.1:8080$suffix;
		}
	}

**Comment by xieruidong521** [comment]
with Laravel Octane

**Comment by rustatian** [comment]
Hey @xieruidong521 👋🏻 

Version 2.x is unsupported at the moment. Could you please check this case on the latest version - 2023.2.2?

**Comment by xieruidong521** [comment]
i tried,has the same problem...
version:rr version 2023.2.2 (build time: 2023-08-10T16:38:44+0000, go1.21.0), OS: windows, arch: amd64

**Comment by xieruidong521** [comment]
@rustatian

**Comment by rustatian** [comment]
@xieruidong521 I've tried this URL:
```
storage/public:MjAyMy8wOS8yMy9JTVZLWHBLUDFXcGJaSFlEODIxZHJqVjlmSVBNZHNpMWgxOEhEWFlZSURHTE9WNzJ0WUhPc00wdlJHNDQzckdtLmpwZWc=?expires=1695433210&noStr=%242y%2410%24M9IgtLXD983gFt1%2FICXw9uNwXa4Yjy6cKjvsfKZBlYHd0n.rk630q&signature=0951ba3f9e1ac743e51cf4950dff15a9be10bb5ec058d9e6fe68e6482321622c
```
And everything works fine:
![image](https://github.com/roadrunner-server/roadrunner/assets/8040338/6d1c876b-4664-4ed5-b6c0-33ec199d896f)

**Comment by xieruidong521** [comment]
I used command curl and postMan it works too!,but broswer doesn't work , I don't know why,thanks very much!

**Comment by xieruidong521** [comment]
![image](https://github.com/roadrunner-server/roadrunner/assets/28883857/8ec30801-8054-47a4-9ebd-32a31ce08186)

**Comment by xieruidong521** [comment]
@rustatian thanks

**Comment by xieruidong521** [comment]
![image](https://github.com/roadrunner-server/roadrunner/assets/28883857/f581361f-dce1-457b-833e-6859130708d3)

**Comment by xieruidong521** [comment]
![image](https://github.com/roadrunner-server/roadrunner/assets/28883857/8038d88c-c4d2-4650-b5bb-a57bb386830a)
maybe beacase of this

**Comment by xieruidong521** [comment]
![image](https://github.com/roadrunner-server/roadrunner/assets/28883857/ac248409-861e-4ede-a047-b2b1e62da2ee)

**Comment by rustatian** [comment]
@xieruidong521 Might be, looks like that something is broken on a request side. Since this is not a RR bug, I'm closing the issue, but feel free to discuss that here.

**Comment by xieruidong521** [comment]
@rustatian no,I think it's the reason for RR, because using PHP+nginx is normal

**Comment by xieruidong521** [comment]
this is nginx+php
![image](https://github.com/roadrunner-server/roadrunner/assets/28883857/3528c0ff-dfe4-4960-a40a-f6a6636c48ca)

**Comment by xieruidong521** [comment]
![image](https://github.com/roadrunner-server/roadrunner/assets/28883857/98648bbf-3350-413c-bd31-ef57c4dd14f4)

**Comment by rustatian** [comment]
> @rustatian no,I think it's the reason for RR, because using PHP+nginx is normal

Then provide a sample to reproduce the issue 😃 As I mentioned before, the URL from the ticket works fine (see my screenshot).

**Comment by r4m-alexd** [comment]
@rustatian I've faced with the same issue.

### What happened?
I tried to send a request with `application/x-www-form-urlencoded`

### Version (rr --version)
```
rr version 2023.3.12 (build time: 2024-02-29T18:24:07+0000, go1.22.0), OS: linux, arch: amd64
```

### How to reproduce the issue?
I used an example from the [quick-start](https://docs.roadrunner.dev/general/quick-start) 
with the following curl:
```
$ curl --location --globoff "localhost:8080" --header 'Accept: application/json' --header 'Content-Type: application/x-www-form-urlencoded' -d 'test;'
```

.rr.test.yaml
```yaml
version: '3'

server:
  command: "php8.1 psr-worker.php"

http:
  address: 0.0.0.0:8080

logs:
  level: debug
  mode: development
```

psr-worker.php
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Nyholm\Psr7\Response;
use Nyholm\Psr7\Factory\Psr17Factory;

use Spiral\RoadRunner\Worker;
use Spiral\RoadRunner\Http\PSR7Worker;
$worker = Worker::create();

$factory = new Psr17Factory();

$psr7 = new PSR7Worker($worker, $factory, $factory, $factory);

while (true) {
    try {
        $request = $psr7->waitRequest();
        if ($request === null) {
            break;
        }
    } catch (\Throwable $e) {
        $psr7->respond(new Response(400));
        continue;
    }

    try {
        $psr7->respond(new Response(200, [], 'Hello RoadRunner!'));
    } catch (\Throwable $e) {
        $psr7->respond(new Response(500, [], 'Something Went Wrong!'));
        $psr7->getWorker()->error((string)$e);
    }
}

```

final server logs:
```console
$ ./rr serve -c .rr.test.yaml 
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48536, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48533, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48540, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48544, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48538, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48549, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48543, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48545, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48548, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48532, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48541, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48537, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48534, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48539, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48546, "internal_event_name": "EventWorkerConstruct"}
2024-03-26T14:48:17+0000        DEBUG   server          worker is allocated     {"pid": 48542, "internal_event_name": "EventWorkerConstruct"}
[INFO] RoadRunner server started; version: 2023.3.12, buildtime: 2024-02-29T18:24:07+0000
[INFO] sdnotify: not notified
2024-03-26T14:48:17+0000        DEBUG   http            http server was started {"address": "0.0.0.0:8080"}
2024-03-26T14:48:42+0000        ERROR   http            request forming error   {"start": "2024-03-26T14:48:42+0000", "elapsed": 0, "error": "invalid semicolon separator in query"}
2024-03-26T14:48:42+0000        INFO    http            http log        {"status": 500, "method": "POST", "URI": "/", "remote_address": "127.0.0.1:45202", "read_bytes": 5, "write_bytes": 49, "start": "2024-03-26T14:48:42+0000", "elapsed": 0}
```

final client logs:
```console
$ curl --location --globoff "localhost:8080" --header 'Accept: application/json' --header 'Content-Type: application/x-www-form-urlencoded' -d 'test;' -vvv
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: application/json
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 5
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 26 Mar 2024 14:52:07 GMT
< Content-Length: 49
< 
serve_http: invalid semicolon separator in query
* Connection #0 to host localhost left intact

```

**Comment by rustatian** [comment]
Hey @r4m-alexd 👋 
You're violating the standard. You can't use `data;` as the body for the `application/x-www-form-urlencoded` content type.

<img width="844" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/8040338/c1d454a7-53a2-4882-b02b-a5d0b57689f8">

**Comment by rustatian** [comment]
If you wanted to use `data;` as the value, simply use - `key=data;`.

**Comment by xieruidong521** [comment]
Yes, after searching for information, it is true that I did not follow the standard regulations. If sending binary content, it should be using text/plain. I just need to change it to this because I can use nginx+PHP before, which is really amazing.

**Comment by xieruidong521** [comment]
thanks！ @rustatian @r4m-alexd

**Comment by GityaMan** [comment]
Hello. Can you tell me how correct it is to return error 500 if the problem is in the user's request?

I encountered a problem: someone scans the application for vulnerabilities and the server periodically returns a 500 response. This triggers alerts, although the problem is not in the server.

Has anyone solved a similar problem?
