### ISSUE TITLE
[🧹 CHORE]: Add support summary metric type

### ISSUE THREAD

**Issue by agratushniy** [roadrunner-server/roadrunner#1746]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

The [rpc interface](https://github.com/roadrunner-server/metrics/blob/0e0626cf5b0379a14c2f5ebe6a75e995ed5da893/rpc.go#L225) has the ability to declare summary, but there is no such possibility in the [php library](https://github.com/roadrunner-php/metrics/blob/3.x/src/Collector.php). Please add :)

**Comment by rustatian** [comment]
Hey @agratushniy 👋🏻 
This issue related to the PHP library, I'll move it to the `roadrunner-php` organization.

**Comment by rustatian** [comment]
https://github.com/roadrunner-php/issues/issues/21
