### ISSUE TITLE
[🧹 CHORE]: Do not log sdnotify events unless sdnotify is used

### ISSUE THREAD

**Issue by rauanmayemir** [roadrunner-server/roadrunner#1756]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

I don't use sdnotify, but now my logs have an info message:
```
[INFO] sdnotify: not notified
```

I believe this information is only relevant if sdnotify is used and enabled.

**Comment by rustatian** [comment]
Hey @rauanmayemir 👋🏻 
Just use the `-s` flag to turn on silent startup mode.

**Comment by rauanmayemir** [comment]
But I don’t need a silent mode, I do want RR to log all the relevant information.

**Comment by rustatian** [comment]
This is not possible to determine whether user made a mistake and forget to use `NOTIFY_SOCKET` or other type of error occurred during the `notifyd` startup routine. Thus, this log is under the general silent flag.

**Comment by rauanmayemir** [comment]
You're saying sdnotify is not an optional feature, but a bundled one?
I wish it hadn't been always-on, containers do not use systemd.

**Comment by rustatian** [comment]
It is a bundled option, but if you don't specify `NOTIFY_SOCKET` or starting RR w/o systemd, RR won't be able to use it and this won't lead to any issues during the startup.

**Comment by rauanmayemir** [comment]
A new feature has been added that works basically automagically for those who needs it.
But for those who can't or don't use it, RR throws noise in the logs.

Your suggestion is to just silent everything altogether. 🤷‍♂️

**Comment by rustatian** [comment]
This is just a startup log. No other (especially plugin) logs are affected. Only `RoadRunner server was started` + `sdnotify` + some other core RR logs. Userspace logs are not impacted by this option.
