### ISSUE TITLE
[💡 FEATURE REQUEST]: OTLP support for gRPC

### ISSUE THREAD

**Issue by rauanmayemir** [roadrunner-server/roadrunner#1782]
### Plugin

GRPC

### I have an idea!

Trace collection for gRPC is currently not supported.

While the spiral side of the trace could be done manually, there will still be a lag on the RR side.
Would be nice to have it for RR, too.

**Comment by rustatian** [comment]
Hey @rauanmayemir :wave: 
Traces for the `gRPC` can be configured via env variables for the RR at the moment. We have an updated stats handler [attached](https://github.com/roadrunner-server/grpc/blob/master/server.go#L51).
Better support via `otel` plugin will be added in `2024.1.0`.

**Comment by rauanmayemir** [comment]
@rustatian Which env vars should I use? I'd like to add at least some basic otel support.

**Comment by rustatian** [comment]
@rauanmayemir  Here you are: [link](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/)
I didn't test them, tho. You may try to play with them, but the real support for the OTEL will be added in `v2024.1.0`.
