### ISSUE TITLE
[💡 FEATURE REQUEST]:  `Arm64` Debian build

### ISSUE THREAD

**Issue by stevenbrookes** [roadrunner-server/roadrunner#1785]
### Plugin

None

### I have an idea!

First off thanks for this great piece of software.  Any chance you could add an Arm64 Debian .deb build file similar to the amd64 .deb file that's available.  It just makes it all easier for us to manage!

**Comment by rustatian** [comment]
Hey @stevenbrookes :wave: 
Sure, `arm64` is tier1 support. I'll provide `.deb` files shortly :+1:

**Comment by stevenbrookes** [comment]
Excellent appreciate it!

**Comment by rustatian** [comment]
@stevenbrookes Done, I'll push release today - `2023.3.6`.

**Comment by rustatian** [comment]
@stevenbrookes Done, you may download the `arm64` deb from the release: https://github.com/roadrunner-server/roadrunner/releases/tag/v2023.3.6

**Comment by stevenbrookes** [comment]
Than you very much  - tested and working fine on  6.1.0-13-cloud-arm64 #1 SMP Debian 6.1.55-1 (2023-09-29) aarch64

**Comment by rustatian** [comment]
Enjoy RR :heart:
