### ISSUE TITLE
[💡 FEATURE REQUEST]: Symfony 7 support

### ISSUE THREAD

**Issue by nunomaduro** [roadrunner-server/roadrunner#1798]
### Plugin

None

### I have an idea!

Seems that https://github.com/roadrunner-php/cli does not have (and is not being tested against) Symfony 7 support. I've tried to pull the repository locally, but it requires me to upgrade Psalm in your project + raises a bunch of issues regarding Psalm. Wondering if someone from the roadrunner team have plans to tackle this task soon?

**Comment by rustatian** [comment]
Hey @nunomaduro 👋 

Let me address this issue to our PHP team. Thanks for noting that 👍

**Comment by rustatian** [comment]
Moved to the PHP issues repo: https://github.com/roadrunner-php/issues/issues/27
