### ISSUE TITLE
[🧹 CHORE]: Beanstalk jobs driver errors log

### ISSUE THREAD

**Issue by SerhiiMova** [roadrunner-server/roadrunner#1804]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

A communication error written by the beanstalk driver interferes with the perception of logs and their processing, I would like to see the possibility of configuring or simply filtering errors of this type

<img width="1504" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/108236991/f183dc00-752f-4b23-af44-1d3c9fa24a77">

**Comment by rustatian** [comment]
Hey @SerhiiMova 👋 
Planned for `v2023.3.8`, release date: 14.12.2023.
