### ISSUE TITLE
[🐛 BUG]: Basic example does not work

### ISSUE THREAD

**Issue by suityou01** [roadrunner-server/roadrunner#1819]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I followed the example

### Version (rr --version)

2023.3.8

### How to reproduce the issue?

Create a dockerfile like so

```Dockerfile
FROM ghcr.io/roadrunner-server/roadrunner:2023.3.8 AS roadrunner
FROM php:8.2-cli as phpbuild

RUN apt-get update && apt-get install -y \
    zip \
    iputils-ping

COPY --from=roadrunner /usr/bin/rr /usr/local/bin/rr

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

# Install php dependencies
RUN docker-php-ext-install sockets

FROM phpbuild

WORKDIR "/app"

# USE THE RR
COPY .rr.yaml .
COPY worker.php .
COPY composer.json .

RUN composer install

EXPOSE 80

CMD rr serve -c .rr.yaml
```
Create an .rr.yaml file

```yaml
version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

http:
  address: "0.0.0.0:8080"

logs:
  level: error
```

Create a composer file

```json
{
    "require": {
        "spiral/roadrunner-cli": "^2.6"
    }
}
```

Create a php file

```php
<?php

use Spiral\RoadRunner;
use Nyholm\Psr7;

include "vendor/autoload.php";

$worker = RoadRunner\Worker::create();
$psrFactory = new Psr7\Factory\Psr17Factory();

$worker = new RoadRunner\Http\PSR7Worker($worker, $psrFactory, $psrFactory, $psrFactory);

while ($req = $worker->waitRequest()) {
    try {
        $rsp = new Psr7\Response();
        $rsp->getBody()->write('Hello world!');

        $worker->respond($rsp);
    } catch (\Throwable $e) {
        $worker->getWorker()->error((string)$e);
    }
}

```
Run it.

### Relevant log output

```shell
handle_serve_command: Function call error:
	serve error from the plugin *http.Plugin stopping execution, error: static_pool_allocate_workers: WorkerAllocate: EOF
```

**Comment by rustatian** [comment]
Hey @suityou01 👋 
I think that you also need `spiral/roadrunner-worker` and `spiral/roadrunner-http` packages. You may try to execute a regular `php` command, like `php worker.php` and you'll see the reason of `EOF` error. Unfortunately, when starting child process and it exists on some initial error, there are no errors except just `EOF`.

**Comment by suityou01** [comment]
Hi @rustatian thank you I will try this. The bug is in the documentation then?

**Comment by rustatian** [comment]
Probably. Please point me where did you find this example, and I'll double-check and fix it.

**Comment by suityou01** [comment]
https://github.com/roadrunner-server/roadrunner?tab=readme-ov-file#docker

**Comment by suityou01** [comment]
This fixed my issue. Thanks.

**Comment by rustatian** [comment]
> This fixed my issue. Thanks.

Cool 👍 I'll add missing packages to the README and enjoy RR ❤️

**Comment by rustatian** [comment]
Docs have been improved: b707643f9ebfbeb0fb80bc970f310e8302dba3b5. Thanks, @suityou01 👍
