### ISSUE TITLE
[💡 FEATURE REQUEST]: HTTP  log middleware separate configuration

### ISSUE THREAD

**Issue by zaishui15** [roadrunner-server/roadrunner#1832]
### Plugin

HTTP

### I have an idea!

I want to add my fields to the HTTP logs, such as recording each request with the current logged in user. There seems to be no good way now
```
l.log.Info("http log",
	zap.Int("status", bw.code),
	zap.String("method", r.Method),
	zap.String("URI", r.RequestURI),
	zap.String("remote_address", r.RemoteAddr),
	zap.Int("read_bytes", bw.read),
	zap.Int("write_bytes", bw.write),
	zap.Time("start", start),
	zap.Duration("elapsed", time.Since(start)))
```
i want to
```
l.log.Info("http log",
	zap.Int("status", bw.code),
	zap.String("method", r.Method),
	zap.String("URI", r.RequestURI),
	zap.String("remote_address", r.RemoteAddr),
	zap.Int("read_bytes", bw.read),
	zap.Int("write_bytes", bw.write),
	zap.Time("start", start),
	zap.Duration("elapsed", time.Since(start)),
	zap.String("user", "loginUser")))
```

**Comment by rustatian** [comment]
Hey @zaishui15 👋 
Looks like this feature request is a more personal request, than a community requested feature.
To add a specific field(s) to the logs, you may fork the original HTTP plugin. Add any number of your project-specific args to the logs and build RR with [Velox](https://github.com/roadrunner-server/velox), [docs](https://roadrunner.dev/docs/customization-build/current/en). This binary would be the same as we provide in the releases, except the HTTP plugin would be replaced by your custom plugin.

**Comment by rustatian** [comment]
If you need further assistance, feel free to join our [Discord](https://discord.gg/spiralphp) server.
