### ISSUE TITLE
[💡 FEATURE REQUEST]: `musl` arm64 binary `[blocked by GitHub ARM action runners]`

### ISSUE THREAD

**Issue by YOU54F** [roadrunner-server/roadrunner#1875]
### Plugin

None

### I have an idea!

Hello related to https://github.com/roadrunner-server/roadrunner/issues/258

could you please, if possible publish musl arm64 variants of the roadrunner & protoc-gen-php-grpc

I maintain a project written in rust, which creates shared libraries which client libraries can load.

We have recently published musl based artifacts, and I am trying to integrate with pact-php's test suite, but one example requires roadrunner.

The AMD64 test run with the current musl binaries is green 🎉 , I just require ARM64 binaries to get a full green build for my ARM64 test runs.

I can skip the test for now, but I noted you have existing arm64 binaries so I would hope it's not a big ask.

Happy to drop in a PR if you wish.

Thanks all!
Saf

**Comment by rustatian** [comment]
Hey @YOU54F 👋 
Sure, I'll update the build pipeline 😃

**Comment by YOU54F** [comment]
cheers my good man!

**Comment by rustatian** [comment]
@YOU54F 👋 
I expected that GitHub already have `arm64` Ubuntu images... Only private beta exists, atm. btw, we're not using `CGO`, so I think you can use `linux-arm64` binaries until GitHub publishes the `arm64` action runners.

**Comment by YOU54F** [comment]
Ahh yes, there is a private beta 

https://resources.github.com/devops/accelerate-your-cicd-with-arm-and-gpu-runners-in-github-actions/

I've signed up but awaiting an invite.

I try and use qemu where possible to build for arm64 with docker, but I've actually tested with a few golang projects and the linux built executables work fine on alpine without a specific musl flavour (built and released with goreleaser) so will test out the regular linux-arm64 binaries. 

Cheers for the having a look buddy, appreciate it!

**Comment by rustatian** [comment]
Looks like we're ready to go: https://github.blog/2024-06-03-arm64-on-github-actions-powering-faster-more-efficient-build-systems/

**Comment by YOU54F** [comment]
ooooh windows too! we've been spoilt by github

**Comment by YOU54F** [comment]
> These runners are available to our customers on our GitHub Team and Enterprise Cloud plans. We expect to begin offering Arm runners for open source projects by the end of the year

doh! lil bit later then

**Comment by YOU54F** [comment]
i think i am going to close this now, the current linux built arm64 works fine for musl at least in my usecase when running it with docker and qemu in linux

**Comment by rustatian** [comment]
Got u 👍
