### ISSUE TITLE
[💡 FEATURE REQUEST]: RPC call to return all available storages

### ISSUE THREAD

**Issue by FluffyDiscord** [roadrunner-server/roadrunner#1886]
### Plugin

KV

### I have an idea!

Example situation:

In Symfony (PHP) I want to get all available storages and set up cache services for each.

Currently I have to manually specify all storage names and their types somewhere else than in .rr.yaml. Changing their names or swapping .rr.yaml for different environments then can be bothersome and may introduce unfortunate errors.

Now if I had a way to get all available storages with their types, or better yet, their whole configuration (basically what can be found in .rr.yaml), I could dynamically map storages by their respective type and/or other properties, making integration ever so smoother.

We could then drop the same application, with the same app environment on a multiple servers with different RR's and kv's and it would automatically take the first available without any hard coded stuff, for example.

**Comment by rustatian** [comment]
Hey @FluffyDiscord 👋 
You already can use `rpc.Config` RPC call to get a whole configuration available to RR in the `yaml` format. This is not the same as having the list of KV storages, but can be deduced from the config easily.

**Comment by FluffyDiscord** [comment]
Oh I wasn't aware of that. Then this FR is not valid. Thank you.

**Comment by rustatian** [comment]
@FluffyDiscord https://docs.roadrunner.dev/php-worker/rpc#available-rpc-methods 😃

**Comment by FluffyDiscord** [comment]
You know I can't read 🤦 🔫
