### ISSUE TITLE
[🐛 BUG]: !BADKEY error on service name with dot (.)

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/roadrunner#1894]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

if service name contains dot (.) then rr fail.

I didn't find any mention about this in [docs](https://roadrunner.dev/docs/plugins-service/current/en)

### Version (rr --version)

version: 2023.3.12, buildtime: 2024-02-29T18:24:06+0000

### How to reproduce the issue?

```yaml
# rr.yaml
service:
  "boom.":
    command: "echo 'hello'"
    exec_timeout: "10s"
    remain_after_exit: true
    process_num: 1
```

### Relevant log output

```shell
[INFO] RoadRunner server started; version: 2023.3.12, buildtime: 2024-02-29T18:24:06+0000
[INFO] sdnotify: not notified
{"time":"2024-03-28T16:01:28.179604595Z","level":"ERROR","msg":"plugin returned an error from the Serve method","!BADKEY":"exec: no command","plugin":"*service.Plugin"}
error: exec: no command
plugin: *service.Plugin
  my-app exited with code 1
```

**Comment by rustatian** [comment]
Hey @gam6itko 👋 
You're using binary build for different architecture. E.g.: musl-linux binary with glibc env.

**Comment by rustatian** [comment]
As for the dots: they're not allowed in yaml, not in the RR. `boom.` parsed by `yaml` like `boom.<no value>` or `boom.command.<echo>`.
BTW: docs nowadays are here: https://docs.roadrunner.dev

**Comment by rustatian** [comment]
Docs are here for that: https://docs.roadrunner.dev/general/config

<img width="975" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/8040338/d0a282a0-417a-4496-ad35-a2ff9c99b226">

**Comment by gam6itko** [comment]
same case here https://github.com/roadrunner-server/roadrunner/issues/1529

**Comment by rustatian** [comment]
Yep 😃 
<img width="665" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/8040338/aaaf966f-8241-40eb-a305-d1cf3645e8a4">
