### ISSUE TITLE
[🐛 BUG]: Jobs. OTEL. rr not recognizes job header `traceparent` and create a new one.

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/roadrunner#1935]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I have sandbox with two applications `app-producer`, `app-consumer`.

https://github.com/gam6itko/spiral-app-sandbox/commit/740565da37ac7a38ad787708140945e588b00fd6

`app-producer` push job to rr.kafka pipeline with one `traceparent` headers. RR not recognizes it and creates a new one and place it to headers `Traceparent` and `Uber-Trace-Id`.
`app-consumer` send traces to otel-collector with `Traceparent` generated by RR, but assumed that it will `app-producer traceparent`.

Produce and Consume events must be linked by one trace-id. But they dont.

![image](https://github.com/roadrunner-server/roadrunner/assets/3841197/c537b2e9-69f8-46b5-afa3-b5a8497372c1)

### producer

`890824b0c7efe8fd9fdfe07f54fa6351`

![image](https://github.com/roadrunner-server/roadrunner/assets/3841197/1124916d-132f-4020-9cf0-5ef5654ddd72)

### consumer

`5a60f81ab969aaf3d49652ce38115abf`
![image](https://github.com/roadrunner-server/roadrunner/assets/3841197/3695ee52-4f0c-4adb-afe1-d499db6bdd73)

### kafka message headers
![image](https://github.com/roadrunner-server/roadrunner/assets/3841197/1f35c268-8e1f-45bb-9cf8-d0c9ecfac5f9)

```json
{
	"rr_pipeline": "kafka_produce",
	"rr_job": "foo-bar",
	"traceparent": "00-890824b0c7efe8fd9fdfe07f54fa6351-cfb7fae4c7ffe91d-01",
	"rr_priority": "\n\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
	"Traceparent": "00-5a60f81ab969aaf3d49652ce38115abf-e4768d9b724573cf-01",
	"Uber-Trace-Id": "5a60f81ab969aaf3d49652ce38115abf:e4768d9b724573cf:0:1"
}
```

### sf dump

![image](https://github.com/roadrunner-server/roadrunner/assets/3841197/f2796cc8-ff11-4d4f-807d-8c1ee7c00e2e)

### Version (rr --version)

RoadRunner server started; version: 2024.1.2, buildtime: 2024-05-16T19:48:53+0000

### How to reproduce the issue?

https://github.com/gam6itko/spiral-app-sandbox/commit/740565da37ac7a38ad787708140945e588b00fd6

```shell
docker compose up -d
```

```http
GET localhost:8080/produce/kafka
```

### Relevant log output

```shell
there is some warnings

2024-06-06T11:03:57+0000     DEBUG   server          worker is allocated     {"pid": 43, "max_execs": 1, "internal_event_name": "EventWorkerConstruct"}
2024-06-06T11:03:57+0000     DEBUG   jobs            job was pushed successfully     {"ID": "29517f2d-d3b1-4fc2-b30a-9bb284b71217", "pipeline": "kafka_produce", "driver": "kafka", "start": "2024-06-06T11:03:57+0000", "elapsed": 2}
2024-06-06T11:03:57+0000     INFO    server          OpenTelemetry: [warning] attribute with non-primitive or non-homogeneous array of primitives dropped: http.url in /srv/vendor/open-telemetry/sdk/Common/Attribute/AttributesBuilder.php(90)

2024-06-06T11:03:57+0000     INFO    server          OpenTelemetry: [warning] attribute with non-primitive or non-homogeneous array of primitives dropped: http.headers in /srv/vendor/open-telemetry/sdk/Common/Attribute/AttributesBuilder.php(90)
```

**Comment by rustatian** [comment]
Hey @gam6itko 👋
`Traceparent` is a canonical header name used across OTEL compatible systems.
`traceparent` is a W3C header.

RR can read and propogate both types of headers, but it doesn't expect them from the external jobs systems. Thus this is not a bug an should be reported as a feature request, thanks.

**Comment by rustatian** [comment]
To clarify: RR propagates these headers with gRPC and HTTP plugins. But for JOBS plugin, there is no such an expectation, that the client library send a trace. Thus RR always start a new one. If there is no OTEL plugin specified, RR will use noop trace (e.g. filled with zeroes).

**Comment by gam6itko** [comment]
@rustatian even if I send the `Traceparent` header from `sf` the RR will replace it by the new one. I can give you a proofs if it needs.

**Comment by rustatian** [comment]
> But for JOBS plugin, there is no such an expectation, that the client library send a trace. Thus RR always start a new one.

**Comment by gam6itko** [comment]
@gam6itko Do I understand correctly that I need to create feature request for the ability to pass one `Trace-Id` through chain of  rr-services?

**Comment by rustatian** [comment]
`Trace-Id` is only one part, thus no. 
You may create a feature request to support receiving `OTEL` spans from the external senders for the JOBS plugins (eg memory, kafka, amqp, etc).
