### ISSUE TITLE
[🐛 BUG]: Roadrunner does not create queues for amqp pipelines

### ISSUE THREAD

**Issue by l-x** [roadrunner-server/roadrunner#1952]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Roadrunner does not declare (create) queues for amqp pipelines, even when configured to consume from.

As far as I can tell this is caused by https://github.com/roadrunner-server/amqp/blob/df3105dbedda689cfd1b7ed44e9e37c10753a446/amqpjobs/driver.go#L461

When declaring RabbitMQ queues in passive mode a channel exception will be raised, if the queue does not exist already. Using `QueueDeclare` instead of `QueueDeclarePassive` will prevent this behaviour.

### Version (rr --version)

rr version 2024.1.5 (build time: 2024-06-20T19:10:43+0000, go1.22.4), OS: linux, arch: amd64 (and previous versions)

### How to reproduce the issue?

- Declare a amqp pipeline in rr config where the queue does not exist (yet) in RabbitMQ
- Start Roadrunner server
- Call `rr workers` in the terminal -> no pipeline information output -> Roadrunner errorlog
- Queue not declared in RabbitMQ

### Relevant log output

```shell
{"level":"DEBUG","ts":"2024-06-24T11:59:25+0000","logger":"amqp        ","msg":"redialer stopped"}
{"level":"ERROR","ts":"2024-06-24T11:59:25+0000","logger":"amqp        ","msg":"pipeline connection was closed, redialing","error":"Exception (404) Reason: \"NOT_FOUND - no queue 'queue_name_here' in vhost '/'\"","pipeline":"pipeline_name_here","driver":"amqp","start":"2024-06-24T11:59:25+0000"}
{"level":"INFO","ts":"2024-06-24T11:59:25+0000","logger":"amqp        ","msg":"amqp dial was succeed. trying to redeclare queues and subscribers"}
{"level":"INFO","ts":"2024-06-24T11:59:25+0000","logger":"amqp        ","msg":"queues and subscribers was redeclared successfully"}
{"level":"INFO","ts":"2024-06-24T11:59:25+0000","logger":"amqp        ","msg":"connection was successfully restored","pipeline":"pipeline_name_here","driver":"amqp","start":"2024-06-24T11:59:25+0000","elapsed":3}
{"level":"INFO","ts":"2024-06-24T11:59:25+0000","logger":"amqp        ","msg":"redialer restarted"}
```

**Comment by rustatian** [comment]
Hey @l-x 👋 
This is the intended behavior. `State` method call expects for the queue to already exist. For example, if you're using the pipeline as a Push only. Having `QueueDeclare` in that case, will create a Queue which is assumed to be already created. 
When starting consumption, if you did not declare `consume` in the configuration for the pipeline, or created a pipeline on-the-fly from PHP JOBS client, you should call a [`resume`](https://github.com/roadrunner-server/amqp/blob/df3105dbedda689cfd1b7ed44e9e37c10753a446/amqpjobs/driver.go#L390) method. It has the same name in the `roadrunner-php/jobs` PHP package.


EDIT: PHP method: https://github.com/roadrunner-php/jobs/blob/0013e1ea4e90cf876f532f5e6c7f9b5b7ed4109f/src/Jobs.php#L66

**Comment by l-x** [comment]
Hey @rustatian, thanks for your quick answer! That makes perfect sense, of course. However, I am afraid that the output of `rr workers` is faulty. In my case, the section `Jobs of [jobs]:` is missing completely as soon as the `QueueDeclarePassive` returns an error.

**Comment by rustatian** [comment]
Yeah, I think it would be worth showing pipelines with error as well as pipelines without. Thanks for the suggestion 👍
