### ISSUE TITLE
[🐛 BUG]: RoadRunner not respecting `num_workers` configuration on `http`

### ISSUE THREAD

**Issue by DenisJunio** [roadrunner-server/roadrunner#1968]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I encountered an issue where the `num_workers` setting in the `.rr.yaml` configuration file is not being respected for the HTTP service. Despite setting `num_workers` to `1`, RoadRunner is still spawning workers based on the number of CPU cores.

**Expected Behavior:**
RoadRunner should respect the `num_workers` setting and spawn only 1 worker as configured.

**Current Behavior:**
RoadRunner spawns multiple workers based on the number of CPU cores, ignoring the `num_workers` configuration for the HTTP service. Interestingly, the `num_workers` setting works correctly for the `jobs` service.

### Version (rr --version)

2024.1.5

### How to reproduce the issue?

 1. Configure as follows: [.rr.json](https://github.com/user-attachments/files/16171088/default.rr.json) (converted from `.rr.yaml`)
 2. Run the command `rr workers` to check the number of workers:
    ```bash
    rr workers
    ```
![image](https://github.com/roadrunner-server/roadrunner/assets/38760003/f907c8ab-aa28-425b-b8de-4fdc75fde1b0)

 3. Run the command `rr reset` and `rr workers` to check the number of workers again:
     ```bash
    rr reset
    rr workers
    ```

**Additional Information:**
- The issue is observed when running inside a Docker container with PHP 8.3. The configuration works correctly for the `jobs` service but not for the `http` service.

**Comment by rustatian** [comment]
Hello @DenisJunio 👋 

Are you using `.rr.yaml` or `.rr.json` for that service in the Docker?

BTW: There is no `reload` plugin.

**Comment by rustatian** [comment]
I tried to use your configuration (in json) as I see only 1 worker:
<img width="1499" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/8040338/c9431f51-e00f-43bd-8acb-68506b0cda93">

1. Double check if you don't have any RoadRunner instance listening on the same port (this is possible to start 2+ RR instances on the same port).
2. Try to check on the separate environment (to exclude environment issue). E.g.: start RR with the same configuration locally.

**Comment by DenisJunio** [comment]
Thank you for the quick response and assistance.

I will conduct more tests on my side as it appears the issue might be related to my configuration, particularly with Laravel Octane. Based on this, I will close the issue for now.

Thanks for your help!

**Comment by rustatian** [comment]
Sure, feel free to join our Discord server if you'd have additional questions 😃
