### ISSUE TITLE
[🐛 BUG]: Logs from workers are not written to STDERR

### ISSUE THREAD

**Issue by hotrush** [roadrunner-server/roadrunner#1991]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Doc says

> Logger Plugin is responsible for collecting logs from server plugins and PHP application workers' STDERR and displaying them in the RoadRunner STDERR/STDOUT

But it doesn't happen.

### Version (rr --version)

rr version 2024.2.0 (build time: 2024-07-25T13:25:02+0000, go1.22.5), OS: linux, arch: amd64

### How to reproduce the issue?

```
logs:
  level: error
  mode: production
```

From php code write smth to STDERR:

```
fwrite(STDERR, $message . PHP_EOL);
```

Nothing appears in container logs.

Also it appears when using `$worker->getWorker()->error($message);` 

### Relevant log output

```shell
php-1  | [INFO] RoadRunner server started; version: 2024.2.0, buildtime: 2024-07-25T13:25:02+0000
php-1  | [INFO] sdnotify: not notified
```

**Comment by rustatian** [comment]
Hey @hotrush 👋 
You need to configure a separate channel for the `server` plugin with `level: info`. All worker related logs have `info` severity and `server` plugin is responsible for that.
Docs: https://docs.roadrunner.dev/docs/logging-and-observability/logger#channels

**Comment by hotrush** [comment]
It works, thanks.

**Comment by rustatian** [comment]
I'll update the docs to clarify that case. It is for sure not obvious.

**Comment by rustatian** [comment]
Updated: https://docs.roadrunner.dev/docs/logging-and-observability/logger
