### ISSUE TITLE
[💡 FEATURE REQUEST]: AMQP driver supports Publisher Confirms

### ISSUE THREAD

**Issue by algirdasci** [roadrunner-server/roadrunner#2014]
### Plugin

JOBS

### I have an idea!

Idea is to implement AMQP [Publisher Confirms](https://medium.com/@anvarnurmatov/rabbitmq-quorum-queue-message-loss-aa5a30acdee5) functionality. This would enable guaranteed message delivery to the broker, especially useful in remote rabbitmq install or applications with unstable network. 

Links:

- Go [example](https://github.com/rabbitmq/amqp091-go/blob/main/_examples/producer/producer.go#L116) of Publisher Confirms
- RabbitMQ QQ [losing messages](https://medium.com/@anvarnurmatov/rabbitmq-quorum-queue-message-loss-aa5a30acdee5)
- Discussed [here](https://github.com/orgs/roadrunner-server/discussions/2012)

**Comment by rustatian** [comment]
Hey @algirdasci 👋 
Thank you for the proposal, adding it to the `v2024.3` milestone.

**Comment by rustatian** [comment]
Implemented in the latest AMQP plugin, will be released as planned.
