### ISSUE TITLE
[🐛 BUG]: RPC call `informer.Workers` rise error after receiving the request

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#2019]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

### Version (rr --version)

rr version 2024.2.1 (build time: 2024-09-12T16:25:02+0000, go1.23.1), OS: linux, arch: amd64

### How to reproduce the issue?

Typical config:

```
http:
    address: 0.0.0.0:8080
    pool:
        debug: 1
```

Use [worker example from docs](https://docs.roadrunner.dev/docs/php-worker/worker#simple-http-worker).

```
...

$rpc = new RPC(Relay::create('tcp://127.0.0.1:6001'));

$result = $rpc->call('informer.Workers', 'http'); // <-------------------   Successful call 

fwrite(STDERR, print_r($result, true));                 <-------------------   Log { workers:[] }

while (true) {
    try {
        $request = $psr7->waitRequest();       // <------------------------ Request receiving here
        if ($request === null) {
            break;
        }
    } catch (\Throwable $e) {
        $psr7->respond(new Response(400));
        continue;
    }

    try {
        $result = $rpc->call('informer.Workers', 'http');  // <------------------------ Error

        $psr7->respond(new Response(200, [], $result));
    } catch (\Throwable $e) {
        $psr7->respond(new Response(500, [], 'Something Went Wrong!'));
        $psr7->getWorker()->error((string)$e);
    }
}
```

### Relevant log output

```shell
[INFO] RoadRunner server started; version: 2024.2.1, buildtime: 2024-09-12T16:25:02+0000
2024-10-05T14:48:48.236561487Z [INFO] sdnotify: not notified
2024-10-05T14:48:48.236923335Z {"level":"debug","ts":1728139728236568069,"logger":"http","msg":"http server was started","address":"0.0.0.0:8080"}
2024-10-05T14:48:50.596414456Z {"level":"debug","ts":1728139730596155838,"logger":"server","msg":"executing in debug mode, worker will be destroyed after response is received"}
2024-10-05T14:48:50.609991129Z {"level":"info","ts":1728139730609767171,"logger":"server","msg":"Array\n(\n    [workers] => Array\n        (\n        )\n\n)\n"}
2024-10-05T14:48:50.610292529Z {"level":"debug","ts":1728139730610168242,"logger":"server","msg":"worker is allocated","pid":21,"max_execs":1,"internal_event_name":"EventWorkerConstruct"}
2024-10-05T14:48:50.619299958Z {"level":"debug","ts":1728139730619089358,"logger":"server","msg":"sending stop request to the worker","pid":21}
2024-10-05T14:48:50.621867299Z {"level":"debug","ts":1728139730621762487,"logger":"server","msg":"worker stopped","pid":21}
2024-10-05T14:48:50.622121704Z {"level":"info","ts":1728139730621932360,"logger":"http","msg":"http log","status":500,"method":"GET","URI":"/","URL":"/","remote_address":"172.18.0.1:48756","read_bytes":0,"write_bytes":21,"start":1728139730595936801,"elapsed":25}
```

**Comment by rustatian** [comment]
Hey @Kaspiman 👋 
This is not a bug, `informer.Workers` is an internal API and should not be used in the worker (it may work, but this is not intentional), especially in the debug mode, where there are no workers.

**Comment by Kaspiman** [comment]
@rustatian 

Should be removed this section from docs? https://docs.roadrunner.dev/docs/php-worker/rpc#calling-rpc-methods

**Comment by rustatian** [comment]
Not the whole section, for sure, but `informer.Workers`.

**Comment by rustatian** [comment]
btw @Kaspiman, just remembered, you may check this project: https://github.com/roadrunner-php/birddog, IIRC, here you may find informer.Workers RPC call. I'm just not sure, if that call is performed by the regular PHP worker. IIRC it is performed from the service (but I'm not sure).

**Comment by Kaspiman** [comment]
> btw @Kaspiman, just remembered, you may check this project: https://github.com/roadrunner-php/birddog, IIRC, here you may find informer.Workers RPC call. I'm just not sure, if that call is performed by the regular PHP worker. IIRC it is performed from the service (but I'm not sure).

https://github.com/roadrunner-php/birddog/blob/9a61b153d92921c6fec6a8c07bdbbcd17d62bbc9/app/src/Module/Informer/Command/WorkersHandler.php#L28

Roughly the same, but not in a `while` cycle after receiving request. Maybe just fix this bug and make it possible to call the method after receiving a request? You won't have to fix packages, make alternative methods, correct documents, etc.

**Comment by rustatian** [comment]
There is nothing to fix here, because you're trying to call this method when there are no workers (aka debug mode). I mentioned this in the first response.
Try to call this API in the regular mode.

**Comment by Kaspiman** [comment]
I tried to reproduce the problem without debug mode with num_workers = 1. The server freezes completely and does not respond to requests.

Normal output:

```
plugin was started	{"address": "tcp://127.0.0.1:6001", "list of the plugins with RPC methods:": ["informer", "resetter", "metrics", "app", "lock"]}
2024-10-25T12:18:44.987416776Z worker is allocated	{"pid": 13, "max_execs": 0, "internal_event_name": "EventWorkerConstruct"}
2024-10-25T12:18:44.987684109Z http server was started	{"address": "0.0.0.0:8080"}
2024-10-25T12:18:45.036677589Z [INFO] RoadRunner server started; version: 2024.2.1, buildtime: 2024-09-12T16:25:02+0000
2024-10-25T12:18:45.036708854Z [INFO] sdnotify: not notified
```

Freezed output:
```
plugin was started	{"address": "tcp://127.0.0.1:6001", "list of the plugins with RPC methods:": ["lock", "informer", "resetter", "app", "metrics"]}
```

That occurs here (call is not succesfull, nothing prints to stderr):
```
$rpc = new RPC(Relay::create('tcp://127.0.0.1:6001'));

$result = $rpc->call('informer.Workers', 'http'); // <-------------------   Error
```

**Comment by Kaspiman** [comment]
Do you need a ready-made repository with a demonstration of the problem? @rustatian

**Comment by rustatian** [comment]
I understand the case, but I don't think this is a problem. Here is my explanation:
1. This is an internal API, and it'd be removed from the docs for sure, I just need some time to do that.
2. When you're trying to perform that RPC call (specifically, outside the worker as you're shown in your sample), RR is still initializing workers. In this step, RPC plugin is not ready yet, and this call hangs on the internal mutex. I guess, that we have a thread (here or in Discord) when I am explaining, that this is an internal API. I can't hide it completely unfortunately. But it should be used only by RR CLI.

To get the info about worker we have metrics. If you need some metric, which we don't have atm, please, send us a FR to add this metric (or PR).

**Comment by rustatian** [comment]
I really want to help you, and this is not like I'm refusing to recognize this issue as a bug and fix it. This is just a documentation issue.
