### ISSUE TITLE
[💡 FEATURE REQUEST]: Introduce/revive JWT middleware in HTTP plugin

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#2025]
### Plugin

HTTP Middleware (any)

### I have an idea!

Often in microservices it is required to validate JWT. Perhaps this functionality was previously in RR. Maybe we will return it in 2025?

These is JWT mention -> https://roadrunner.dev/features

Some jwt packages required https://github.com/search?q=org%3Aroadrunner-server+jwt&type=code&p=1

**Comment by rustatian** [comment]
duplicate: #912 
You may send your proposal in the ^ ticket.

**Comment by rustatian** [comment]
But yeah, need to remove mentions from the features page. Thanks.
