### ISSUE TITLE
[🐛 BUG]: Failed to call goridge in the swoole coroutine

### ISSUE THREAD

**Issue by anhao** [roadrunner-server/roadrunner#2031]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Same issue https://github.com/roadrunner-server/roadrunner/issues/1951

But in v4.2 there is the same problem

### Version (rr --version)

spiral/goridge:v4.2

### How to reproduce the issue?

on swoole

**Comment by rustatian** [comment]
Hey @anhao 👋 
It is merged in v3.2.1, not 4.2.

**Comment by anhao** [comment]
> Hey @anhao 👋 It is merged in v3.2.1, not 4.2.

Why wasn't version 4.2 merged ?

**Comment by rustatian** [comment]
Not sure, but try v3.2.1 first, I'll double-check why it wasn't merged into 4.x branch.

**Comment by rustatian** [comment]
@anhao Have you tried v3.2.1?

**Comment by anhao** [comment]
> @anhao Have you tried v3.2.1?

v3.2.1 is ok
