### ISSUE TITLE
[🐛 BUG]:  Error 'empty ID is not allowed' for 'forceRelease' method.

### ISSUE THREAD

**Issue by fugikzl** [roadrunner-server/roadrunner#2050]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

RoadRunner\Lock\Lock::forceRelease(string $resource): bool - method throws RPC exception with message "Error 'empty ID is not allowed'". It may be caused by check in https://github.com/roadrunner-server/lock/blob/05729ecc410d2c61a7124da03c6d7d235063c284/rpc.go#L105

### Version (rr --version)

2024.2.1

### How to reproduce the issue?

Set up RPC server in .rr.yaml. Create lock for resource and try forceRelease() method.

### Relevant log output

```shell
Spiral\\Goridge\\RPC\\Exception\\ServiceException: Error 'empty ID is not allowed' on tcp://0.0.0.0:6001
```

**Comment by rustatian** [comment]
Hey @fugikzl 👋 
Yeah, agree, you're right. `ForceRelease` method does not require `ID`.

**Comment by rustatian** [comment]
@fugikzl Fixed, will be released in the `v2024.3`.

**Comment by rustatian** [comment]
@fugikzl Currently, you may pass any dummy non-empty ID with the payload to bypass this limitation until v2024.3 release. This would also work with the updated version, but ID would be simply skipped. So, pre-2024.3 and post-2024.3 won't introduce any breaking changes.

**Comment by fugikzl** [comment]
@rustatian got it, thanks!

**Comment by fugikzl** [comment]
If anyone has met with same problem before the release, here is the example of temporary solution:
```php
            \Spiral\Goridge\RPC\RPC::create($connection)->call('lock.ForceRelease', [
                'resource' => $resource,
                'id' => 'any-string'
            ]);
```
Explanation: roadrunner-php/lock library calls `lock.ForceRelease` without passing any ID that causes error, so passing dummy id in the direct rpc call may be considered as a temporary solution
