### ISSUE TITLE
[💡 FEATURE REQUEST]: server.on_init with an option to crash the server

### ISSUE THREAD

**Issue by wizardist** [roadrunner-server/roadrunner#2075]
### Plugin

Server

### I have an idea!

Per documentation,

> If the on_init command fails (i.e., returns a non-zero exit code), RoadRunner will log the error but continue execution. This ensures that a failure during initialization does not interrupt the application's operation.

While this makes sense for many use cases, we want to use `server.on_init` to make preflight checks when a Kubernetes pod starts. While we could do an init container instead, we want to use RoadRunner as much as possible, and crashing PID 1 would work just fine in our case.

I suggest to add `server.on_init.fail_on_error` boolean configuration option that will relay the exit code from the on_init script and will exit the master process, thereby crashing the container.

I hope that others with containerized environments may benefit from this too. I would like to get a go-ahead from the community before we submit a pull request with necessary changes.

**Comment by rustatian** [comment]
Hey @wizardist 👋🏻 
Yeah, it makes sense for me. Will be in the next release.

**Comment by wizardist** [comment]
@rustatian just to confirm, have you assigned the FR to yourself to work on it? 😊 This is really great.

**Comment by rustatian** [comment]
Sure, why not 😄 You want to try it yourself?

**Comment by wizardist** [comment]
@rustatian we're onboarding RoadRunner for production workloads, and making the teams familiar with the RR codebase is beneficial. Let me check with the Legal, and if we have a green light to contribute to RR codebase, I'll assign one of my team members, or myself, to this issue.

Let me unassign you from it so there's clarity on this. If we hit a red light, I'll ping you and re-assign you back. But I really doubt it will happen. ☺️

**Comment by rustatian** [comment]
I've already implemented this 😄 
But still, if you wanted to help, just reach out to me (or just use `help-wanted` issues tag search).

**Comment by rustatian** [comment]
You may build your RR binary with Velox (roadrunner-server/velox + you may check our docs for the instuction) with that change (just use `master` branch for the `server` plugin) if you wanted to try it right now, w/o waiting for the release.

**Comment by AleksandrKosovS** [comment]
Thank you. I built it from master and it successfully fails if init script returns error with `exit_on_error` true 👍
