### ISSUE TITLE
[💡 FEATURE REQUEST]: temporal workflow max_worker_memory

### ISSUE THREAD

**Issue by root-aza** [roadrunner-server/roadrunner#2076]
### Plugin

Temporal

### I have an idea!

Workflow workers can also have memory leaks, I suggest implementing a similar mechanism as in activities

<details>
  <summary>Memory metrics</summary>
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/2afe1aad-94de-4542-94fc-47d1a1f31afd">
</details>

**Comment by rustatian** [comment]
Hey @root-aza 👋🏻 
WF workers are very sensitive to restarts and to allow users to have memory leaks. Restarting WF worker will invalidate sticky cache, lead to restart temporal workers and activity workers. WF worker is the same as Activity and Supervisor is turned off on it on purpose.
