### ISSUE TITLE
[🐛 BUG]: v2024.3 doesn't contain OpenTelemetry plugin

### ISSUE THREAD

**Issue by r4m-alexd** [roadrunner-server/roadrunner#2088]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

### Version (rr --version)

rr version 2024.3.0 (build time: 2024-12-05T18:39:42+0000, go1.23.4), OS: linux, arch: amd64

### How to reproduce the issue?

Just download the latest release, then add `otel` middleware to http:
```
http:
  middleware: [otel]
```

As I see it was removed [here](https://github.com/roadrunner-server/velox/commit/ec02e1ce5374b922019227294274a36c2d242d7c#diff-a2cfa1d64f198201c89ad627a5683eb6f5f43cd3379769ceed24ebdc29f9ce09L40)

### Relevant log output

```shell
{"level":"warn","ts":1733833593866754701,"logger":"http","msg":"requested middleware does not exist","requested":"otel"}
```

### UPD
I tried other older versions and got the same warning. Am I doing something wrong or the [docs](https://docs.roadrunner.dev/docs/logging-and-observability/otel#configuration) is outdated?

**Comment by rustatian** [comment]
Hey @r4m-alexd 👋🏻 
Docs: [link](https://docs.roadrunner.dev/docs/logging-and-observability/otel)
You should add the `otel` plugin configuration.

**Comment by r4m-alexd** [comment]
@rustatian Yes, I just found out that I placed `otel` config under the `http` key instead of root.
But the error message is invalid, it says that the middleware doesn't exist, but it does.
`The middleware config doesn't exist` - that's the right message.

**Comment by rustatian** [comment]
Middleware does not exist from the RR point of view. Because since you don't have a configuration for the `otel` plugin, for the RR it does not exist (removed from the initialization tree). So, RR can't find it and reports that the middleware you specified in the configuration does not exist.
