### ISSUE TITLE
[🧹 CHORE]: Possibility to disable activity workers

### ISSUE THREAD

**Issue by cv65kr** [roadrunner-server/roadrunner#2089]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

I have a case where we don't need activities, let's consider it as a workflow:
```
#[WorkflowInterface]
class Workflow
{
    private Data $data;
    private bool $signal = false;
    
    private Statistics $statistics;
    
    #[WorkflowMethod(name: 'Test')]
    public function run()
    {
        while (true) {
            yield Workflow::awaitWithTimeout(CarbonInterval::minutes(35), fn () => $this->signal);
            $this->signal = false;
            
            // Do some operations
            $this->statistics = new Statistics(); // Output of operations
            
            // Continue as new
        }
    }

    #[SignalMethod]
    public function register(array $data): void
    {
        $this->data->add($data);
        $this->signal = true;
    }

    #[QueryMethod]
    public function statistics(): Statistics
    {
        return $this->statistics;
    }
}
```

So in general we are calculating and aggregating signals and returns statistics.

In this particular case we need only `workflow worker` in temporal plugin. 

If you set up 0 activity workers it will set up 5 one.

To save resources and avoid unused activity workers, would be nice to have possibility to disable activity workers.

**Comment by rustatian** [comment]
Hey @cv65kr 👋🏻 
Yeah, it makes sense 👍🏻
