### ISSUE TITLE
[🐛 BUG]: Centrifuge cannot decode non-json payload due to forced json decoding

### ISSUE THREAD

**Issue by FluffyDiscord** [roadrunner-server/roadrunner#2099]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Sometimes, I do not want to send JSON payload, but only a plain string. Can support be added? Maybe something like `rawData` would be great and also dont let it die when json decoding fails

![image](https://github.com/user-attachments/assets/8616e3b7-7284-41f8-8675-16b580b0a6ae)

### Version (rr --version)

2024.3.1

### How to reproduce the issue?

send non json payload to centrifuge

**Comment by rustatian** [comment]
Hey @FluffyDiscord 👋🏻 RoadRunner does not care about the data. It just re-sends it to the underlying worker.
I think, you need to move this issue to the roadrunner-php issues, not roadrunner-server org. BTW, you may also send a PR to the PHP centrifugo package 😉

**Comment by FluffyDiscord** [comment]
@rustatian ah yes, my bad, I somehow got here, but wanted to open the issue on the php side, issue is indeed there, sorry!
