### ISSUE TITLE
[💡TESTS]: Fuzz testing

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/roadrunner#261]
Add fuzz-testing for golang (PHP ?) part of the application
https://github.com/dvyukov/go-fuzz
@wolfy-j

**Comment by 48d90782** [comment]
https://go.googlesource.com/proposal/+/master/design/draft-fuzzing.md

**Comment by rustatian** [comment]
Supported since Go 1.18. Already used in RR tests.
