### ISSUE TITLE
[Q]: Environment variable not parsed

### ISSUE THREAD

**Issue by viktorprogger** [roadrunner-server/roadrunner#875]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I've added a `DOMAIN` environment variable to the `http.ssl.acme.domains[0]` in the config, and on `./rr serve --dotenv=.env` I've seen this error:
> [${DOMAIN}] Obtain: subject does not qualify for a public certificate: ${DOMAIN}

```yml
http:
  pool:
    num_workers: ${RR_WORKERS} # This one works fine
  ssl:
    acme:
      domains:
        - ${DOMAIN} # This one doesn't work
```

### Version

2.6.6

### Relevant log output

```shell
{"level":"error","ts":1639868192.9881098,"logger":"obtain","caller":"certmagic@v0.15.2/async.go:120","msg":"will retry","error":"[${DOMAIN}] Obtain: subject does not qualify for a public certificate: ${DOMAIN}","attempt":1,"retrying_in":60,"elapsed":0.001143204,"max_duration":2592000,"stacktrace":"github.com/caddyserver/certmagic.doWithRetry\n\tgithub.com/caddyserver/certmagic@v0.15.2/async.go:120\ngithub.com/caddyserver/certmagic.(*Config).obtainCert\n\tgithub.com/caddyserver/certmagic@v0.15.2/config.go:572\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync\n\tgithub.com/caddyserver/certmagic@v0.15.2/config.go:427\ngithub.com/spiral/roadrunner-plugins/v2/http.ObtainCertificates\n\tgithub.com/spiral/roadrunner-plugins/v2@v2.6.7/http/acme.go:76\ngithub.com/spiral/roadrunner-plugins/v2/http.(*Plugin).serve\n\tgithub.com/spiral/roadrunner-plugins/v2@v2.6.7/http/plugin.go:205\ngithub.com/spiral/roadrunner-plugins/v2/http.(*Plugin).Serve.func1\n\tgithub.com/spiral/roadrunner-plugins/v2@v2.6.7/http/plugin.go:131"}
```

**Comment by rustatian** [comment]
@viktorprogger Hey. This is not a bug. RR doesn't support env variables passed this way.

**Comment by viktorprogger** [comment]
@rustatian And what's the right way? I remember you said I shouldn't write `$`, but it didn't work for `num_workers` without the `$` symbol.

**Comment by rustatian** [comment]
I said, that you can set env variable with `{VAR}` syntax in the RR1, but in the RR2 this feature wasn't implemented (no requests to implement this).
`--dotenv` flag can be used to read your env variables.
`-o http.address=YOU_NEW_ADDRESS_HERE` to overwrite address in the `.rr.yaml`.

If you want to see additional functionality here, please, open the feature request.
