### ISSUE TITLE
[💡 FEATURE REQUEST]: API so RoadRunner could be included in other servers

### ISSUE THREAD

**Issue by Richard87** [roadrunner-server/roadrunner#878]
### Plugin

Server

### I have an idea!

Hi!

I love the concept of RoadRunner, but is currently using Caddy as frontend for php-fpm, s3proxy and some other snacks... 

I'm currently working on a esbuild plugin for caddy to bundle and serve assets directly...

I would *love* to create a roadrunner plugin as well, but right now it would be super hacky to manipulate the Serve command...

Specifically, I would love a
- `rr := NewRoadRunner(options)` method, that returns a RR instance and 2 methods
- `rr.ServeHTTP(w http.ResponseWriter, r *http.Request) error` (or similar)
- `rr.Close()` for any cleanup that is required. 

Would you be interrested in a PullRequest for this functionality?

Alternativly, would it be possible to bring esbuild as a plugin to RoadRunner, and s3proxy as a plugin? :)

**Comment by rustatian** [comment]
Hey @Richard87. Thanks for the proposal 👍🏻 
As you said, you use caddy with PHP-FPM, and RR also supports FCGI. So, you can use the `http` plugin with fcgi endpoint and pass the requests from the Caddy to the RR -> https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L704

> it would be super hacky to manipulate the Serve command

You don't need to manipulate the `Serve` command. You can create a RR plugin as a completely separate plugin with any server (HTTP, http/2, fcgi, etc) inside (with your own `Serve`).

It would be great if you create a plugin for the RR. To do that, you may have a look at our container (used in the RR) -> https://github.com/spiral/endure, and our standard plugins: https://github.com/spiral/roadrunner-plugins (have a look at the readme). Do not hesitate to contact me if you need any help with creating a plugin, feel free to join our discord server and ping me (rustatian) in the roadrunner channel -> https://discord.gg/TFeEmCs

**Comment by Richard87** [comment]
Thanks for answering so quick!

RR with FCGI might solve all my problems! Thanks, I'll also take a look at the plugin documentation, maybe I get some inspiration!
