### ISSUE TITLE
[💡FEATURE REQUEST]: Decouple Application Logging and Roadrunner Logging

### ISSUE THREAD

**Issue by Bibob7** [roadrunner-server/roadrunner#880]
### Plugin

Server

### I have an idea!

I have a problem when using Application logging since it is currently coupled to the logs config of the server plugin.
I can only see application logs, when log level of roadrunner is at least `info`

Additionally, also the log encoding influences my application logging, where I already use a json formatter with monolog.

I would like to simply write application logs untouched to stderr.

In the server plugin folder, I found in oninit.go:

```
func (p *Plugin) Write(data []byte) (int, error) {
	p.log.Info(utils.AsString(data))
	return len(data), nil
}
```

Why not do something like this instead?:

```
func (p *Plugin) Write(data []byte) (int, error) {
	fmt.Print(utils.AsString(data))
	return len(data), nil
}

**Comment by rustatian** [comment]
Update for the 2.7 release: `info` log level for the `stderr/stdout` (as it was). `error` log level for the worker allocate failure. All other internal messages are logged at the `debug` log level (including TTL, execTTL, memory, etc).
So, at the `info` log level you'll see only the startup message (also will be an option to turn it off).

**Comment by odombrovskyi-dev** [comment]
Hi, I have the same issue with the RR 2.7.0. Is there any way to disable this message?
```
[INFO] RoadRunner server started; version: 2.7.0, buildtime: 2022-01-13T14:22:48+0000
```

**Comment by rustatian** [comment]
> Hi, I have the same issue with the RR 2.7.0. Is there any way to disable this message?
> 
> ```
> [INFO] RoadRunner server started; version: 2.7.0, buildtime: 2022-01-13T14:22:48+0000
> ```

Hey @adombrovsky. There is no way to disable this message in the current version. In the 2.8 will be a flag to start silently.
