### ISSUE TITLE
[💡 FEATURE REQUEST]: newrelic: option to consider some http codes as not error codes

### ISSUE THREAD

**Issue by arku31** [roadrunner-server/roadrunner#899]
### I have an idea!

Currently, if the status code is f.e. 412, it will be reported as an error. However, for some applications, 412 is the expected result and it should not be reported as an error but as a normal transaction. The solution for this is to

Add a configuration field to the newrelic section: 
```error_status_codes: 500,424```

If the status code is listed there, mark the transaction as the error. Otherwise, report it as a normal, successful transaction.

**Comment by rustatian** [comment]
Sorry @arku31, that's not possible due to the new_relic library architecture.
