### ISSUE TITLE
[💡FEATURE REQUEST]: Prometheus metrics for queued and rejected requests (load monitoring)

### ISSUE THREAD

**Issue by victor-sudakov** [roadrunner-server/roadrunner#908]
**Problem description**

It is currently not possible to detect/monitor the situations when 1) Roadrunner has started queuing requests because  simultaneous requests >  num_workers and 2) "no free workers in the pool" condition has happened. It is actually possible to see the "no free workers in the pool" condition in the log but only post factum.

**The solution I'd like**
I'd like to have additional Prometheus metrics for load monitoring.

1. The metric for Situation 1 should show the current queue size (0 if no request queuing is happening).
2. The metric for Situation 2 is more difficult to define. Ideally, it should not only count the number of "no free workers in the pool" occurrences already happened, but allow to predict the situation by calculating "required seconds in the backend" or something.

But even just exposing the number of "no free workers in the pool" occurrences to Prometheus could be useful.

**Describe alternatives you've considered**
1. There is no viable alternative for Situation 1.
2. You can grep the logs for  "no free workers in the pool" and use it as a hint to increase num_workers or allocation timeout, but this solution has no predictive power.

**Comment by Warxcell** [comment]
+1 for exposing number of free/busy workers. It would allow to scale in advance, if there is some I/O blocking in workers, and they  all become busy.

**Comment by rustatian** [comment]
> +1 for exposing number of free/busy workers. It would allow to scale in advance, if there is some I/O blocking in workers, and they all become busy.

No +1 please, put the thumb up in the first message. Thanks.

**Comment by rustatian** [comment]
@victor-sudakov Have you tried the new grafana dashboard: https://github.com/roadrunner-server/roadrunner/tree/master/grafana?

**Comment by rustatian** [comment]
1. Done: https://github.com/roadrunner-server/prometheus/blob/master/plugin.go#L52 (have a look at the stable branch for the grafana dashboards)
2. Since we providing the latency: https://github.com/roadrunner-server/prometheus/blob/master/plugin.go#L71 and the `queue_size`, this metric could be easily calculated on-demand.
Thanks.
