### ISSUE TITLE
[💡FEATURE REQUEST]: Enhance CORS support

### ISSUE THREAD

**Issue by hustlahusky** [roadrunner-server/roadrunner#909]
Current CORS headers settings doesn't covers my use cases.

First of all I want a support of multiple allowed origins (or even any origin) with credentials enabled. Currently `http.headers.cors.allowed_origin = *` and `http.headers.cors.allow_credentials = true` is not working together.

Would be nice if `allowed_origin` can be configured as single origin or array of origins, and option to reflect `Origin` from request header (maybe combination of `allowed_origin = *` and `allow_credentials = true` or some reserved `allowed_origin` value). CORS middleware example in Go, that can acts like described: https://github.com/rs/cors

Second little problem is deprecation message from browser like that, when `allowed_headers = *`:

```
"Authorization" will not be covered by the wildcard symbol (*)in CORS "Access-Control-Allow-Headers" handling.
```

I found out that it can be reflected from `Access-Control-Request-Headers` request header if it specified by client.

**Comment by rustatian** [comment]
Multiply `allowed_origins` now supported. Fixed by the: https://github.com/roadrunner-server/headers/pull/48

> RoadRunner can allow any origin reflected from request header

This is not an expected behavior (and non-standard), origins should be set explicitly. Not planned to implement.
