### ISSUE TITLE
[💡FEATURE REQUEST]: Improve error message when command fails

### ISSUE THREAD

**Issue by alexander-schranz** [roadrunner-server/roadrunner#910]
**Is your feature request related to a problem? Please describe.**

If I'm running roadrunner on a none exist php script the error message is very cryptical:

<details>
<summary>Error Message</summary>

```
2021-10-09T11:19:24.494+0200	ERROR	container/poller.go:16	vertex got an error	{"id": "http.Plugin", "error": "http_plugin_serve: WorkerAllocate:\n\tserver_plugin_new_worker_pool:\n\tstatic_pool_initialize:\n\tstatic_pool_allocate_workers:\n\tfactory_spawn_worker_with_timeout: fetch_pid: CRC mismatch; signal: killed; process_wait: signal: killed"}
github.com/spiral/endure/pkg/container.(*Endure).poll.func1
	github.com/spiral/endure@v1.0.4/pkg/container/poller.go:16
error occurred: http_plugin_serve: WorkerAllocate:
	server_plugin_new_worker_pool:
	static_pool_initialize:
	static_pool_allocate_workers:
	factory_spawn_worker_with_timeout: fetch_pid: CRC mismatch; signal: killed; process_wait: signal: killed, plugin: http.Plugin
handle_serve_command: WorkerAllocate:
	http_plugin_serve:
	server_plugin_new_worker_pool:
	static_pool_initialize:
	static_pool_allocate_workers:
	factory_spawn_worker_with_timeout: fetch_pid: CRC mismatch; signal: killed; process_wait: signal: killed
```
</details>

Example:

```yaml
server:
    command: "php public/none-exist-script.php"
```

**Describe the solution you'd like**

It would be nice to get a nicer error message that example the target script does not exist.

Example php outputs:

> Could not open input file: public/none-exist-script.php

Exit code: 1

Nice to have would be that a `die('test');` or any other exit with output is also shown. There the same `CRC mismatch` is shown.

**Describe alternatives you've considered**

..

**Additional context**

Roadrunner: v2.4.2

**Comment by rustatian** [comment]
Ok guys :) The time has come 😸
Forget about `CRC validation error`... Starting from the `2.10.6` RR will show a user-friendly message `validation failed on the message sent to STDOUT, RR docs: https://roadrunner.dev/docs/known-issues-stdout-crc/2.x/en, invalid message: ...` (RR will display an invalid message on Linux/Mac in full)

This message clearly says that smt went wrong with the `STDOUT`. Also, we will include a link to our docs page in the error: https://roadrunner.dev/docs/known-issues-stdout-crc/2.x/en.
You may add your cases to this page, so other users will likely find their points here.

**Comment by rustatian** [comment]
@samdark 
> Another example:
> 
> ```
> roadrunner_1  | {"level":"info","ts":1635505553.3834863,"logger":"server","msg":"Fatal error: Uncaught Error: Class \"Spiral\\RoadRunner\\Worker\" not found in /app/worker.php:15\nStack trace:\n#0 {main}\n  thrown in /app/worker.php on line 15\n"}
> roadrunner_1  | 2021-10-29T11:05:53.383Z        ERROR   container/poller.go:16  vertex got an error     {"id": "http.Plugin", "error": "WorkerAllocate:\n\tgoridge_frame_receive: EOF"}
> roadrunner_1  | github.com/spiral/endure/pkg/container.(*Endure).poll.func1
> roadrunner_1  |         github.com/spiral/endure@v1.0.6/pkg/container/poller.go:16
> ```
> 
> I'd expect:
> 
> ```
> roadrunner_1  | Fatal error: Uncaught Error: Class "Spiral\RoadRunner\Worker" not found in /app/worker.php:15
>                          Stack trace:
>                              #0 {main} thrown in /app/worker.php on line 15
> ```

Sorry, I missed this message.
To get rid of the messages from the container, you may set the `endure` log level to `panic` https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L1606

And this part of the stacktrace will not bother you 😃.
```log
roadrunner_1  | 2021-10-29T11:05:53.383Z        ERROR   container/poller.go:16  vertex got an error     {"id": "http.Plugin", "error": "WorkerAllocate:\n\tgoridge_frame_receive: EOF"}
roadrunner_1  | github.com/spiral/endure/pkg/container.(*Endure).poll.func1
roadrunner_1  |         github.com/spiral/endure@v1.0.6/pkg/container/poller.go:16
```


The second part of your message is a structured log. To receive a raw message, please, set the log mode to `raw`: https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L85
```log
roadrunner_1  | {"level":"info","ts":1635505553.3834863,"logger":"server","msg":"Fatal error: Uncaught Error: Class \"Spiral\\RoadRunner\\Worker\" not found in /app/worker.php:15\nStack trace:\n#0 {main}\n  thrown in /app/worker.php on line 15\n"}
```

**Comment by rustatian** [comment]
@alexander-schranz 
> Nice +1 would it be possible to add the `exit code` o the error message if there was one? Example if doing `die(255);` to show `255` in the error message.

You may see the exit code in the debug mode (I have added a `die(255);` to the test worker's code):
![image](https://user-images.githubusercontent.com/8040338/177775721-aeca006c-ba19-462d-bf07-2ecc0553bae3.png)

**Comment by rustatian** [comment]
@alexander-schranz 

>Nice to have would be that a die('test'); or any other exit with output is also shown. There the same CRC mismatch is shown.

In the latest version (2.10.6), if you add `die('test');` to the worker's code, you'll see the messages in the `info` logs:
![image](https://user-images.githubusercontent.com/8040338/177776827-829f7e05-4497-4c02-a6f4-3adc8c41557b.png)

```php
while ($req = $psr7->waitRequest()) {
    try {
        $resp = new \Nyholm\Psr7\Response();
        $resp->getBody()->write("hello world");

        die('test'); // <--- BOOM

        $psr7->respond($resp);
    } catch (\Throwable $e) {
        $psr7->getWorker()->error((string)$e);
    }
}
```

**Comment by rustatian** [comment]
Thanks for the collaboration, guys 🤝 . Since everything in this ticket is resolved, I will close it as `done`. It's not locked, so, feel free to reopen it if I missed something.

**Comment by alexander-schranz** [comment]
Nice. Thank you, the result looks promising. Hopefully can test it out soon :)
