### ISSUE TITLE
[💡FEATURE REQUEST]: Get domain list for Let's encrypt not from config

### ISSUE THREAD

**Issue by Alexfilus** [roadrunner-server/roadrunner#913]
I have ~400 subdomains. Now it is working with manual update of wildcard certificate. 
Auto renewal of subdomain's list can simplify support.
Add everything to YAML config looks hard.

Option allows to get domain list from simple file. Domains divided with \n

Ability to read domains from some KV database, or Sqlite3, or from some more complicated file format, might be amazing.

Perfect solution: RR listen changes in domains list, and get new certificates without restarting of RR.

**Comment by rustatian** [comment]
Thanks for the FR @Alexfilus 👍🏻 Since no one commented/liked this FR for the 1.5 years - closing it. (Discussion is not locked)
