### ISSUE TITLE
[💡FEATURE REQUEST]: Support SSE as an alternative to websockets

### ISSUE THREAD

**Issue by steffendietz** [roadrunner-server/roadrunner#921]
Now that we have websockets as a means to provide (bidirectional) push communication from the server to the browser, it would also be nice to support [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) for (unidirectional) push messages.

SSE could potentially use the already existing pub-sub infrastructure of the websockets.

**Additional context**
This was discussed here https://github.com/spiral/roadrunner/discussions/704

**Comment by rustatian** [comment]
We've implemented the bidirectional communication via centrifugo (browser <-> RR <-> PHP): https://github.com/roadrunner-php/centrifugo
Unfortunately, a separate SSE plugin is not planned. Thanks for the FR 👍🏻

**Comment by maximal** [comment]
SSE feature would be fantastic! (Considering that the main RoadRunner competitor, FrankenPHP, has one.)

**Comment by rustatian** [comment]
Hey @maximal 👋 
That's cool, that FrankenPHP supports this 😃 
I'm not against this feature, would be happy to review the PR 😃 
Nowadays, RR supports HTTP response streaming as well as HTTP 103 early hints code.

**Comment by maximal** [comment]
@rustatian, okay, I’ll investigate into this.
