### ISSUE TITLE
[💡FEATURE REQUEST]: Plugin for profiling with pyroscope

### ISSUE THREAD

**Issue by rauanmayemir** [roadrunner-server/roadrunner#922]
**Describe the solution you'd like**

[Pyroscope](https://github.com/pyroscope-io/pyroscope) is a profiling tool that consists of a server and agents that live alongside the app (actually they exec the underlying app, periodically sample the process memory and collect profiling information).

It would be nice to have a RR plugin that handles the agent setup for the workers and forwards the data to the server endpoint that is provided via config.

**Comment by rustatian** [comment]
Thanks for the FR @rauanmayemir 👍🏻. Our PHP team created the official tool to collect profiling/debug information: https://github.com/buggregator/spiral-app, so, others are not planned (but for sure, can be added by the community).
