### ISSUE TITLE
[💡FEATURE REQUEST]: Profiler Module based on xhprof

### ISSUE THREAD

**Issue by wolfy-j** [roadrunner-server/roadrunner#925]
Integrate https://github.com/tideways/php-xhprof-extension as the source of profiling data and pass this data into rr service via RPC. Store data in local db (BoltDB) or memory and share information about application performance via RPC or expose the port. Need UI.

**Comment by rustatian** [comment]
Thanks for the FR 👍🏻. Our PHP team created the official tool to collect profiling/debug information: https://github.com/buggregator/spiral-app, so, others are not planned (but for sure, can be added by the community).
