### ISSUE TITLE
[💡 FEATURE REQUEST]: Documentation improvement

### ISSUE THREAD

**Issue by masterjus** [roadrunner-server/roadrunner#941]
### I have an idea!

I have an idea, listen to me!!

I've got a trouble when set `ttl: 3600` value without `s`. My workers has started to reboot every 3600 milliseconds.

Please mention this in your documentation.

**Comment by rustatian** [comment]
Hey @masterjus, sure, thanks for noting that 👍🏻

**Comment by rustatian** [comment]
@masterjus https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L639, in the configuration reference all `time` keys has the `s` at the end.
