### ISSUE TITLE
[🐛 BUG]: Could not find any available RoadRunner binary version which meets criterio     n

### ISSUE THREAD

**Issue by Yurunsoft** [roadrunner-server/roadrunner#956]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

```shell
vendor/bin/rr get-binary -f 2.5.*
```

### Version

2.5.*

### Relevant log output

```shell
Environment:
   - Version:          2.5.*
   - Stability:        stable
   - Operating System: linux
   - Architecture:     amd64


In GetBinaryCommand.php line 299:
                                                                               
  Could not find any available RoadRunner binary version which meets criterio  
  n (--os=linux --arch=amd64 --stability=stable). Available: v2.5.3, v2.5.2,   
  v2.5.1, v2.5.0                                                               
                                                                               

get-binary [-o|--os [OS]] [-a|--arch [ARCH]] [-f|--filter [FILTER]] [-l|--location [LOCATION]] [-s|--stability [STABILITY]]
```

**Comment by rustatian** [comment]
Hey @Yurunsoft. What `roadrunner-cli` version do you use?

**Comment by Yurunsoft** [comment]
I use v2.1.0

Why: `Starting from the roadrunner-cli v2.1.0 versions of roadrunner binary lower than 2.7.0 are not supported.`

**Comment by rustatian** [comment]
> I use v2.1.0
> 
> Why: `Starting from the roadrunner-cli v2.1.0 versions of roadrunner binary lower than 2.7.0 are not supported.`

1. We moved to the new organization.
2. We support only the latest stable release.

RR doesn't contain BC's, except configuration for the KV described in the 2.5.0 release notes. So, you can safely upgrade to 2.7.3 (latest release)

**Comment by rustatian** [comment]
If you still wanted to use the previous versions, please, use the previous `roadrunner-cli` version.

**Comment by rustatian** [comment]
@Yurunsoft Feel free to reopen this issue if you have any questions about it. Thanks.
