### ISSUE TITLE
[💡 FEATURE REQUEST]: Consume any payload (not only `Jobs` structured) from the `Jobs` drivers

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/roadrunner#979]
### Plugin

JOBS

### I have an idea!

At the moment, `job` drivers consumers are able to accept only the `Jobs` structures (eg payloads accepted from the Jobs `push` RPC call).
I propose to create a set of `<driver_name>_raw` drivers which would be able to consume any payload, pack it into the `Jobs` structure (only for the PHP worker compatibility), and send it to the workers.
Basically, the raw payload will be in the job's `payload` field and the ID field will be autogenerated.

**Comment by steffendietz** [comment]
Good idea.

Wouldn't it make sense to introduce a new `bool` config option called `raw` to the existing drivers?

That way you wouldn't need to introduce the `*_raw` drivers.

**Comment by rustatian** [comment]
Hey @steffendietz 😃 I just don't want to have a complicated logic inside the drivers. From my POV handling raw payloads lead to significant changes inside the driver and might be different payloads (RPC and internal) since we don't use the existing `Jobs` structures. 
But, for sure, I have both options in my mind: a separate driver or some switch inside. This question is: how big will the changes be?

**Comment by Colomix** [comment]
Is very need, roadrunner does not allow integration through RabbitMQ's queues, because jobs require rr_id and rr_job in message's header. Not the fact that another system uses roadrunner jobs for publishing

**Comment by rustatian** [comment]
Ok, it'll be planned for the `2.11` version. Thanks for the feedback.

**Comment by Colomix** [comment]
It would also be useful to give the opportunity to make several connections for jobs. For example, RabbitMQ's vhost for internal bus and vhost for reading external data without headers in messages.

**Comment by rustatian** [comment]
@Colomix You may start a second RR instance to have a second connection.

**Comment by rustatian** [comment]
The feature will be in `v2.10.1`. The name of this option will be `consume_all`. If set to true and if RR was unsuccessful in parsing the incoming payload (`RR_ID` is absent, etc). It'll create a `Job`, based only on the incoming headers and body.
The `Job` name and `pipeline` for this case will be `deduced_by_rr`.

**Comment by rustatian** [comment]
Also, the message will be ack-ed/nack-ed as the usual message, and the message ID will be unique. Priority for such messages is constant and equal to 10 (since we can't deduce or get it from the user).

**Comment by rustatian** [comment]
`consume_all` option will be available for the `amqp`, `sqs`, `beanstalk`, and `nats` drivers.

**Comment by bc-anton-k** [comment]
> The feature will be in `v2.10.1`. The name of this option will be `consume_all`. If set to true and if RR was unsuccessful in parsing the incoming payload (`RR_ID` is absent, etc). It'll create a `Job`, based only on the incoming headers and body. The `Job` name and `pipeline` for this case will be `deduced_by_rr`.

Saved my week. Thanks a lot!
