### ISSUE TITLE
[💡 FEATURE REQUEST]: move from `vendor/bin/rr get` to `COPY --from=spiralscout/roadrunner:2.7.6 /usr/bin/rr /usr/bin/rr`?

### ISSUE THREAD

**Issue by Ocramius** [roadrunner-server/roadrunner#989]
### I have an idea!

While running `vendor/bin/rr get`, I often incur into `403` errors due to rate limits (not authenticated against the github API).

This problem is even starker when setting up roadrunner inside a `Dockerfile` (and its related build).

Is copying the binary (from the correct arch) perhaps a better approach?

```Dockerfile
COPY --from=spiralscout/roadrunner:2.7.6 /usr/bin/rr /usr/bin/rr
```

In practice, the above is:

 * cacheable
 * cache is invalidated correctly when version changes (compared to the always cached `rr get`)
 * compatible with @dependabot and @renovatebot (upgrades will be performed automatically)
 * removes the need for HTTP requests performed from within the build context

Thoughts? I know this is mostly for `docker` users, but it seems like a much simpler installation method, and it would allow the deprecation of the `GetBinaryCommand`, which obviously has limits inherent from the GitHub API.

**Comment by rustatian** [comment]
Hey @Ocramius 👋🏻 Yeah, getting RR from the docker is a good option, many users already apply this approach. Also, would be an option is to use some env variable (`GH_TOKEN` for example for the `rr get`) to raise the limit up to 5000 req/h. This is not implemented yet, I'll discuss that with our PHP team. [Velox](https://github.com/roadrunner-server/velox) for example uses `github_token` option to raise the limit.
